<table width="100%" border="0" cellpadding="5" cellspacing="0"  bgcolor=white >

<tr><td valign=top width=80%> 

	<p>

     <span class=sottotitolopagina><?php echo($stringa[hai_dimenticato_pw]);?><br>

     </span>

	</p>

	 <p><span class=testo><?php echo($stringa[nessun_problema]);?></span></p>



	<form action=invia_pwd.php method=post>

	<span class=testopiccolo><b><?php echo($stringa[email_id]);?>:</b></span> <input type=text maxlength=100 size=35 name=dato_utente> <input type=submit value="OK">

	</form>				

</td></tr>

</table>





<br>
