<table width="94%" align="center">

  <tr> 

    <td height="14" width="22%"> 

      <div align="center"></div>

    </td>

    <td height="14" width="78%"> 

      <span class="titolopagina">Laboratori</span>

	  <br><br>

	  <span class="sottotitolopagina">

	  Corso in rete</span>

	  <br><br>



    </td>

  </tr>

  <tr> 

    <td width="22%"  valign="top"> 

<!--

      <ul>

        <li> 

          <span class="titololink"> 

		  <a href="ftp/">tua area di lavoro</a>

		  </span>

		  <br><br>

        </li>

      </ul>

-->

    </td>

    <td width="78%" valign="top"> 

	<!-- contenuto pagina -->

	<p><span class=testo><b>sezione non ancora attivata</b></span>

	<!-- fine contenuto pagina -->

<p>&nbsp;</p>

      </td>

  </tr>

</table>

<br>
