<p>
<font face="verdana"><b>Cerca risorsa</b></font>
</p>
<p>
[<a href=javascript:history.back()>Indietro</a>]
</p>

<form action="index.php" method="POST">
<input type="hidden" name="risorsa" value="materiali_lista_risorse_trovate">
<table border="0">
	<tr>			
    <tr>
          <td align="right"><font face="verdana" size="-1"><b>Cerca risorsa con identificativo:</b></font></td>
            <td><font face="verdana" size="-1"><input type="text"
            size="20" maxlength=100 name="id_risorsa_cerca"></font></td>
   </tr>
</table>

<br>
    <p><input type="submit" value="CERCA"></p>
</form>
<hr>
