<p><span class=titolopagina>Nuova rubrica</span></p>

<span class=testo>[<a href=index.php?risorsa=gestione_rubriche>Gestione rubriche</a>]</span><br>

  <P> 

  <form action=rubrica_add.php method=post>

    <TABLE border=0 width=600>

      <TR> 

        <TD colSpan=2></TD>

      </TR>

      <TR> 

      <TR> 

        <TD align=right valign=top><span class=testo><b>ID Rubrica:</b></span></TD>

        <TD> 

			<INPUT type="text" maxLength=200 name=id_rubrica 

            size=20> <br><span class=testopiccolo><i>non inserire spazi o caratteri diversi da lettere e numeri</i></span>

        </TD>

      </TR>

      <TR> 

        <TD align=right><span class=testo><b>Denominazione rubrica:</b></span></TD>

        <TD> 

			<INPUT type="text" maxLength=200 name=titolo size=20>

        </TD>

      </TR>



	    <TR> 

        <TD align=right><span class=testo><b>Posizione nell'elenco:</b></span></TD>

        <TD> 

			<INPUT type="text" maxLength=200 name=posizione size=20>

        </TD>

      </TR>

      

	  	  

    </TABLE>

    <BR>

    <P align=center> 

      <INPUT type=submit value="INSERISCI">

    </P>

  </FORM>

  <HR>
