<?php
$nomemese["January"]="Ianuarie";
$nomemese["February"]="Februarie";
$nomemese["March"]="Martie";
$nomemese["April"]="Aprilie";
$nomemese["May"]="Mai";
$nomemese["June"]="Junie";
$nomemese["July"]="Julie";
$nomemese["August"]="August";
$nomemese["September"]="Septembrie";
$nomemese["October"]="Octobrie";
$nomemese["November"]="Novembrie";
$nomemese["December"]="Decembrie";

$stringa[home]="Acasa";
$stringa[forum]="Forum";
$stringa[chat]="Chat";
$stringa[chi_e_in_linea]="Cine este online";
$stringa[posta_interna]="E-Mail";
$stringa[eventi]="Calendar";
$stringa[materiali]="Continut";
$stringa[materiali_test]="Continut & Test";
$stringa[laboratori]="Laborator";
$stringa[cerca]="Cauta";
$stringa[info]="Info";
$stringa[catalogo_corsi]="Catalogul cursului";
$stringa[helpdesk]="Helpdesk";
$stringa[admin]="Administrator";
$stringa[buon_lavoro]="Bunvenit";
$stringa[modifica_profilo]="Schimba parola si alte date personale";
$stringa[statistiche]="Statistici";
$stringa[statistiche_alt]="Statistici despre utilizarile tale de cursuri";
$stringa[logout_alt]="Iesire din Kairos";
$stringa[logout]="X";
/* -------- */

$stringa[gruppo]="Grup";
$stringa[tutor]="Tutore";
$stringa[clicca_per_sapere_chi]="Apasa pentru a identifica persoana";

$stringa[ricevuto_invito]="Ai fost invitat intr-o sesiune de chat";
$stringa[accetto]="Accept";

$stringa[nuovi_messaggi]="Ai un nou mesaj de la";

$stringa[sito_realizzato]="Powered by";
$stringa[piattaforma_per]="platforma e-learning";

$stringa[generale]="General";
$stringa[laboratorio]="Laborator";

$stringa[su_max]="din";

$stringa[pagina_up]="Muta sus";
$stringa[pagina_down]="Muta jos";
$stringa[cancella]="Sterge";
$stringa[modifica]="Modifica";
$stringa[modifica_file]="Modifica Fisier";
$stringa[modifica_pagina]="Modifica pagina web";
$stringa[modifica_sito]="Modifica web site";
$stringa[pagina_web]="Pagina Web";
$stringa[nota]="Nota";
$stringa[file]="Fisier";
$stringa[apri_cartella]="Deschide folder";
$stringa[dir_superiore]="Folder sus";
$stringa[inserisci]="Introduce";
$stringa[copia_indirizzo]="Copie";

$stringa[nuovo]="Nou!";
$stringa[nuovo_interno]="Noutati!";

$stringa[inserisci_tabella]="Introduce Tabel";
$stringa[inserisci_immagine]="Insert Image";
$stringa[inserisci_suono]="Insert Sound";
$stringa[inserisci_flash]="Insert Flash animation";
$stringa[inserisci_video]="Insert Video";
$stringa[crea_link]="Create Link";
$stringa[indentato]="Indent";
$stringa[non_indentato]="Outdent";
$stringa[elenco_numerato]="Lista ordonata";
$stringa[elenco]="Lista aleatoare";
$stringa[allineato_dx]="Aliniaza dreapta";
$stringa[allineato_centro]="Aliniaza central";
$stringa[allineato_sx]="Aliniaza stanga";
$stringa[corsivo]="Italic";
$stringa[sottolineato]="Subliniaza";
$stringa[grassetto]="Bold";
$stringa[redo]="Reface";
$stringa[undo]="Anuleaza";
$stringa[incolla]="Lipeste";
$stringa[copia]="Copiaza";
$stringa[taglia]="Taie";
$stringa[testo]="TEXT";

$stringa[mod_testo]="Ati setat modul TEXT";

$stringa[login]="LOGIN";
$stringa[id]="ID";
$stringa[pw]="PW";
$stringa[dimenticato_pw]="Am uitat parola!";
$stringa[login_atlante]="Trebuie mai inatai sa te <b>loghezi</b>";

$stringa[indietro]="Inapoi";
$stringa[avanti]="Inainte";

$stringa[area_admin]="Area Administrativa";
$stringa[gestione_forum]="Forum Manager";
$stringa[invio_newsletter]="Trimite stiri despre curs";
$stringa[statistiche_corso]="Statistici curs";
$stringa[monitoraggio_corso]="Monitorizare Curs";
$stringa[gestione_materiali]="Content Manager";
$stringa[personalizza_interfaccia]="Personalizeaza Aspectul";
$stringa[gestione_utenti]="User Manager";
$stringa[gestione_corsi]="Manager Curs";
$stringa[nuova_pagina_web]="Noua Pagina Web";
$stringa[nuovo_file]="Fisier Nou";
$stringa[nuova_cartella]="Folder Nou";

$stringa[calendario_eventi]="Calendar Evenimente";
$stringa[nuovo_evento]="Eveniment Nou";
$stringa[lunedi]="Luni";
$stringa[martedi]="Marti";
$stringa[mercoledi]="Miercuri";
$stringa[giovedi]="Joi";
$stringa[venerdi]="Vineri";
$stringa[sabato]="Sambata";
$stringa[domenica]="Duminica";
$stringa[seleziona]="Selecteaza";
$stringa[no_selezione]="Nici un eveniment selectat pentru a sterge.";
$stringa[evento_cancellato]="Eveniment sters";
$stringa[no_modifica]="Nici un eveniment selectat pentru a modifica";

$stringa[gestione_cartella_img]="IMG Folder Manager";
$stringa[cancella_elementi]="Sterge itemii selectati";

$stringa[cerca_utenti]="Cauta user";
$stringa[identificativo]="ID User";
$stringa[nome]="Nume";
$stringa[cognome]="Prenume";
$stringa[prov]="Prov.";
$stringa[citta]="Oras";

$stringa[cerca_forum]="Cauta in forum";
$stringa[inserisci_stringa]="Introduceti macar un cuvant pentru a cauta.";
$stringa[non_trovato]="Nici un rezultat";
$stringa[pagine]="Pagini";
$stringa[cerca_risultati]="Rezultatele Cautarii";
$stringa[num]="N.";
$stringa[utente]="User";
$stringa[manda_messaggio]="trimite mesaj privat catre user";

$stringa[chat]="Chat";
$stringa[chat_intro]="Pentru a intra, apasa pe numele camerei de chat.<br>Numarul din paranteza inidica cati utilizatori se afla in acest moment in camera.";
$stringa[Generale]="General";
$stringa[laboratorio]="Laborator";
$stringa[archivio_chat]="Arcive Chat";

$stringa[hai_dimenticato_pw]="Ai uitat parola?";
$stringa[nessun_problema]="Nici o problema. Scrie adresa de email sau ID-ul de user. Vei primi imediat parola in adresa ta de email";
$stringa[email_id]="Email sau User ID";

$stringa[nuovo_forum]="Forum Nou";
$stringa[id_forum]="Forum ID";
$stringa[posizione]="Ordine";
$stringa[indica_posizione]="scrieti un numar corespunzator pozitiei in care doriti sa puneti forumul in lista ordonata de forumuri";
$stringa[descrizione]="Descriere";
$stringa[tipo]="Tip";
$stringa[corso]="Curs";
$stringa[staff]="Staff";
$stringa[file_allegati]="Atasare fisier";
$stringa[si]="Da";
$stringa[no]="Nu";
$stringa[crea]="CREAZA";

$stringa[tempo]="Timp";
$stringa[oggetto]="Subiect";

$stringa[modifica_forum]="Modifica Forum";
$stringa[qualunque]="oricare";

$stringa[cartella]="Folder";
$stringa[id_file]="File ID";
$stringa[file_caricare]="Fisier pentru upload";
$stringa[livello]="Nivel";
$stringa[pubblico]="Public";
$stringa[registrati]="Inregistrat";
$stringa[parole_chiave]="Cuvinte Cheie";
$stringa[carica]="UPLOAD";

$stringa[id_cartella]="Folder ID";

$stringa[stanza]="Camera";
$stringa[giorno]="Zi";
$stringa[dalle_ore]="De la";
$stringa[alle_ore]="Catre";
$stringa[ok]="OK";

$stringa[pos]="Pos.";
$stringa[num_int]="#Posts";

$stringa[modifica_intervento]="Modifica Post";
$stringa[autore]="Autor";
$stringa[intervento]="Post";
$stringa[allega_file]="Atasare fisier (max. 5MB)";
$stringa[file_allegato]="Fisier atasat";
$stringa[cancella_allegato]="sterge fisier atasat";
$stringa[icona]="Icon";
$stringa[generica]="neutra";
$stringa[domanda]="intrebare";
$stringa[idea]="idee";
$stringa[approvo]="acord";
$stringa[disapprovo]="dezacord";
$stringa[importante]="important";
$stringa[confuso]="confuz";
$stringa[contento]="fericit";
$stringa[triste]="trist";
$stringa[scherzo]="gluma";
$stringa[arrabbiato]="furios";
$stringa[moltoarrabbiato]="foartefurios";
$stringa[fico]="cool";
$stringa[invia_repliche]="Trimite raspunsurile la adresa mea de email";

$stringa[web_forum]="Forum";
$stringa[cerca_forum]="Cauta in forumuri";
$stringa[cerca]="Cauta";
$stringa[risultati_5]="5 rezultate pe pagina";
$stringa[risultati_10]="10 rezultate pe pagina";
$stringa[risultati_20]="20 rezultate pe pagina";
$stringa[risultati_30]="30 rezultate pe pagina";
$stringa[risultati_50]="50 rezultate pe pagina";
$stringa[archivio_faq]="Arhiva la raspunsurile intrebarilor adresate in mod curent";
$stringa[faq]="FAQ";
$stringa[forum_intro]="Pentru a intra apasa pe numele forumului.
In paranteze sunt trecute numarul de postari necitite de tine.
<br>";
$stringa[forum_staff]="Staff forum";
$stringa[forum_generali]="Forum general al platformei";
$stringa[forum_corso]="Forumuri ale Cursurilor";
$stringa[forum_gruppo]="Forumuri ale grupului tau";
$stringa[forum_del_gruppo]="Forumuri ale grupului";
$stringa[forum_del_gruppo_pw]="Forumuri ale grupului de lucru al proiectului"; 

$stringa[nuovo_intervento]="Postare noua";
$stringa[comprimi_struttura]="Inchide toate subiectele";
$stringa[espandi_struttura]="Restrange toate subiectele";
$stringa[vista_cronologica]="Vizualizeaza cronologic";
$stringa[vista_struttura]="Vizualizeaza in functie de subiect";
$stringa[interessanti]="Vizualizeaza pe cele marcate";

$stringa[prec]="Precedent";
$stringa[succ]="Urmator";
$stringa[intervento_sup]="Inapoi la subiect";
$stringa[indice]="Index";
$stringa[replica_intervento]="Raspunde la postare";
$stringa[modifica_intervento]="Modifica postare";
$stringa[cancella_intervento]="Sterge postare";
$stringa[interessante]="Marcheaza postare";
$stringa[non_interessante]="Demarcheaza postare";
$stringa[chi_letto_alt]="Apasa pentru a vizualiza cine a citit postarea";
$stringa[chi_letto]="Cine a citit-o?";
$stringa[da_leggere]="Marcheaza ca necitit";
$stringa[ricopia_faq]="Copiaza in sectiunea FAQ";
$stringa[sposta_in]="Muta in";
$stringa[sposta]="Muta";
$stringa[ha_scritto]="scrie";
$stringa[senza_oggetto]="fara subiect";
$stringa[senza_titolo]="fara titlu";

$stringa[avere_id]="Pentru ID si parola <br>e necesara";
$stringa[registrarsi]="inregistrarea";
$stringa[corsi]="Editii Curs";
$stringa[news_direzione]="Stiri";
$stringa[nuova_news]="Nou";
$stringa[no_primo_piano]="No more at the top";
$stringa[news_iscritti]="Spatiu User";
$stringa[modifica_sezione]="Editeaza aceasta sectiune, posteaza toate noutatile care consideri ca vor fi de interes comunitatii";

$stringa[spazio_web_pers]="Spatiu web personal";
$stringa[cartelle_condivise]="Spatiu web comun";
$stringa[chat_collaborativo]="Chat colaborativ";
$stringa[lavori_corsisti]="Lista de proiecte a utilizatorilor";
$stringa[corsista]="User";
$stringa[sito]="Site";

$stringa[cartella_file]="Fisier director";

$stringa[conf_cancella_pagina]="esti sigur ca vrei sa stergi aceasta pagina web si toate aliasurile?";
$stringa[conf_cancella_lab_sito]="esti sigur ca vrei sa stergi referinta catre acest site web?";
$stringa[conf_cancella_file]="esti sigur ca vrei sa stergi acest fisier?";
$stringa[conf_cancella_cartella]="esti sigur ca vrei sa stergi aces folder si tot continutul sau?";
$stringa[conf_cancella_nota]="esti sigur ca vrei sa stergi aceasta nota?";
$stringa[conf_cancella_link]="esti sigur ca vrei sa stergi acest alias?";

$stringa[gestione_test]="Test manager";
$stringa[sequenza_pubblicazione]="Sarcini ale continutului de curs";
$stringa[sequenza_pubblicazione_comune]="Sarcina comuna din zona de continut";

$stringa[id_pagina_web]="ID Pagina";
$stringa[normale]="Normal";
$stringa[titolo]="Titlu";
$stringa[codice_contenuto]="Continut cod HTML";
$stringa[contenuto]="Continut";

$stringa[inviati]="trimise";
$stringa[ricevuti]="primite";
$stringa[messaggi]="Mesaje";
$stringa[nuovo_messaggio_alt]="Mesaj nou";
$stringa[nuovo_messaggio]="Scrie un mesaj nou";
$stringa[da]="De la";
$stringa[a]="Catre";
$stringa[spedito]="Trimis";
$stringa[letto]="Citit";
$stringa[leggi_messaggio_alt]="Deschide mesajul";

$stringa[modifica_profilo]="Modifica profilul userului";
$stringa[modifica_intro]="";
$stringa[immagine_profilo]="Imagine (GIF/JPG max 100KB)";
$stringa[immagine_profilo_alt]="Apasa pentru a vedea imaginea upload-ata";
$stringa[immagine]="Imagine";
$stringa[password]="Parola";
$stringa[indirizzo]="Adresa";
$stringa[cap]="Cod";
$stringa[scuola]="Scoala";
$stringa[telefono]="Telefon";
$stringa[email]="E-Mail";
$stringa[sitoweb]="Web Site";
$stringa[sesso]="Sex";
$stringa[m]="M";
$stringa[f]="F";
$stringa[eta]="Varsta";
$stringa[interessi]="Interese";
$stringa[qualcosa_di_me]="Ceva despre mine";

$stringa[stanza_di_chat]="Camera de Chat";
$stringa[dialoghi_del]="Chatul de";
$stringa[totale_righe]="Total randuri";
$stringa[totale_utenti]="Total useri";
$stringa[utente]="User";
$stringa[righe]="Randuri";
$stringa[entra_esce]="intra/iesire";

$stringa[crea_news]="creaza stiri";
$stringa[primo_piano]="Top stiri";
$stringa[news]="stiri";
$stringa[facoltativo]="optional";
$stringa[testo]="Continut";
$stringa[modifica_news]="Modifica stiri";

$stringa[giorno]="Ziua";
$stringa[evento_confermato]="Eveniment confirmat.";
$stringa[torna_mese]="Inapoi la luna";

$stringa[registrazione]="Inregistrare";
$stringa[stato]="Rol";
$stringa[id_guida]="(scrisoare si/sau numar doar fara spatii)";
$stringa[registrazione_guida]="Inregistrarea dumneavoastra va fi confirmata de <b>area administrativa</b>.";
$stringa[modifica_ruolo]="Schimba rol pentru a selecta useri";
$stringa[registrazione_manuale]="Noua platforma de inregistrare useri";
$stringa[registrazion_man_guida]="Inregistrarea va fi activata imediat. Trebuie sa informezi userul despre ID-ul si parola sa.";

$stringa[registrato_attesa]="inregistrari in asteptare";
$stringa[id_utente]="User ID";
$stringa[utenti_trovati]="Useri gasiti";
$stringa[nuova_ricerca]="Cautare noua";

$stringa[test]="Test";
$stringa[duplica]="Copiaza";
$stringa[nuovo_test]="Test nou";
$stringa[domande]="Intrebari";
$stringa[duplica_test]="Copiere test";
$stringa[test_modifica]="Modificare test";
$stringa[id_test]="Test ID";
$stringa[verifica]="verifica";
$stringa[sondaggio]="studiu";
$stringa[num_comp]="#ocupat";
$stringa[risultati]="Rezultate";
$stringa[edit]="Editare";
$stringa[edit_test]="Testare editare";
$stringa[aggiungi_domanda]="Adauga intrebare";

$stringa[nuova_domanda_test]="Noua intrebare din test";
$stringa[chiusa]="Alegeri multimple";
$stringa[risposta_multipla]="Raspunsuri multiple";
$stringa[vero_falso]="Adevarat/Fals";
$stringa[inserimento]="Completeaza-spatiile";
$stringa[associazione]="Potriveste";
$stringa[aree_immagine]="Zone de imagine";
$stringa[aperta]="Raspuns scurt";
$stringa[scelta]="Optiuni";
$stringa[punteggio]="Scor";
$stringa[chiedi_altro]="Solicita altele pentru a specifica";
$stringa[commento_post]="Feedback";

$stringa[modifica_domanda_test]="Modifica intrebare din test";

$stringa[conferma_del_test]="sunteti sigur ca vreti sa stergeti testul si completarile?"; 

$stringa[compilazione_test]="Completeaza testul";
$stringa[test_inesistente]="Testul nu exista";
$stringa[altro_specificare]="Alta, specificate care";

$stringa[risposta_fornita]="Raspunsul tau a fost";
$stringa[risposte_possibili]="Posible raspunsuri (scor corespondent)";
$stringa[note]="Nota";
$stringa[punteggio_ottenuto]="Ai obtinut urmatorul scor";
$stringa[punteggio_max]="din care";
$stringa[questionario_registrato]="Testul a fost inregistrat. Va multumim!";

$stringa[risultati_test]="Rezultatele testului";
$stringa[data_prima]="Prima completare de date";
$stringa[data_ultima]="Ultima completare de date";
$stringa[tot_compilazioni]="Completari totale";
$stringa[risposte_aperte]="Deschide raspunsuri";
$stringa[altro]="Alte";
$stringa[non_risposto]="Fara raspuns";

$stringa[elenco_compilazioni]="Listare completari test";
$stringa[data]="Data";
$stringa[questionario_compilato]="Test completat";

$stringa[no_file]="fara fisier";
$stringa[dettaglio_risposta]="Raspunsuri la intrebare";

$stringa[web]="Web";
$stringa[file]="Fisier";
$stringa[link]="Link";
$stringa[materiali_non_pubblicati]="Continutul nu este atribuit cursului";
$stringa[materiali_pubblicati]="Continutul este atribuit cursului";
$stringa[materiali_non_pubblicati_comune]="Continutul nu este atribuit zonei comune";
$stringa[materiali_pubblicati_comune]="Continutul este atribuit zonei comune";

$stringa[nuovo_corso]="Curs nou";
$stringa[edizione]="Editare";
$stringa[iscritti]="#Subscris";
$stringa[status]="Status";
$stringa[nuova_edizione]="editie noua";

$stringa[id_corso]="ID Curs";
$stringa[nuova_edizione_corso]="Noua editie a cursului";
$stringa[id_edizione]="ID Editie";
$stringa[data_inizio]="Data de incepere";
$stringa[durata]="Durata";
$stringa[mesi]="luni";
$stringa[giorni]="zile";
$stringa[attiva]="activ";
$stringa[inattiva]="inactiv";

$stringa[modifica_corso]="Modifica Curs";
$stringa[modifica_edizione_corso]="Modifica Editie Curs";

$stringa[iscrizioni_effettuate]="El/Ea s-a inscris la urmatoarele cursuri";
$stringa[gestione_iscrizioni]="Manager de inscrieri la curs";
$stringa[nuovo_gruppo]="Grup Nou";
$stringa[id_gruppo]="Grup ID";
$stringa[id_tutor]="Tutor ID";
$stringa[opzionale]="optional";
$stringa[modifica_gruppo]="Modifica grup";

$stringa[gestione_gruppo]="Manager grup";
$stringa[utenti_attesa]="Useri neinscrisi in grup";
$stringa[utenti_iscritti]="Useri atribuiti grupului";
$stringa[utenti_attesa_pw]="Useri atribuibili proiectului";
$stringa[utenti_iscritti_pw]="Useri atribuiti proiectului";

$stringa[statistiche_corso]="Statistici curs";
$stringa[dal]="De la";
$stringa[al]="La";
$stringa[sessioni]="Sesiuni";
$stringa[interventi_forum]="Postari forum";
$stringa[durata_media]="Timp mediu";
$stringa[durata_totale]="Timp total";
$stringa[scritti]="Scris";
$stringa[letti]="Citit";
$stringa[righe_chat]="Randuri chat";
$stringa[risorse_piattaforma]="Resursa platformei";

$stringa[no_privilegi]="Nu puteti accesa aceasta resursa.";
$stringa[no_accesso]="Nu puteti accesa acest continut";
$stringa[dettaglio_statistiche]="Detalii ale statisticii cursului";
$stringa[interventi_scritti]="Postari scrise pe forum";
$stringa[interventi_letti]="Citeste postari forum";

$stringa[ricopia_in_faq_corso]="Copiere post in rubrica FAQ a cursului";
$stringa[domanda_f]="Intrebare";
$stringa[risposta_f]="Raspuns";

$stringa[modifica_faq_corso]="Modifica FAQ curs";
$stringa[faq_corso]="FAQ curs";
$stringa[nuova_faq]="Nou";

$stringa[errore_gif_jpg]="Doar fisierele gif si jpg sunt permise";
$stringa[errore_max_file]="Dimensiunea fisierului este prea mare.";
$stringa[errore]="Eroare";
$stringa[errore_intro]="Ne pare rau, am obtinut urmatoarele erori";
$stringa[errore_file_esiste]="Fisier exista deja.";

$stringa[errore_forum_esiste]="ID de forum exista deja";
$stringa[errore_id_forum_richiesto]="Trebuie sa definesti un ID de forum";
$stringa[errore_solo_lettere]="Doare litere, numere si _ pot fi utilizare pentru ID";
$stringa[errore_gruppo_corso_richiesto]="Trebuie sa selectati un curs inaintea crearii unui forum de curs";
$stringa[errore_lab_corso_richiesto]="Trebuie sa selectati un curs inaintea crearii unui forum de laborator";

$stringa[indirizzo_file_img]="Adresa fisierului imagine";
$stringa[indirizzo_file_img_guida]="Adresa trebuie sa inceapa cu <b>http://...</b> si sa indice un fisier <b>.gif</b> or <b>.jpg</b> file.";
$stringa[elenco_img_alt]="Deschide lista de imagini uploadate pentru a selecta una sau a uploada o alta.";
$stringa[elenco_img]="Lista imagini uploadate";

$stringa[editor]="Editor";
$stringa[invia]="Trimis";
$stringa[lascia]="Lasa";
$stringa[riprendi]="Take";
$stringa[nuovo_e]="Nou";
$stringa[salva]="Salveaza";
$stringa[apri]="Deschide";

$stringa[errore_manca_id]="ID Lipsa";
$stringa[manca_id]="ID Lipsa";

$stringa[id_risorsa]="Resursa ID";
$stringa[popup]="PopUp";
$stringa[larghezza_finestra]="Latime fereastra";
$stringa[altezza_finestra]="Inaltime fereastra";
$stringa[apro_link]="Link target";
$stringa[stessa_finestra]="in aceeasi fereastra";
$stringa[altra_finestra]="in alta fereastra";

$stringa[errore_id_esiste]="ID exista deja";
$stringa[errore_manca_titolo]="Titlu Lipsa";
$stringa[errore_manca_descrizione]="Descriere Lipsa";
$stringa[errore_manca_file]="Fisier Lipsa";

$stringa[errore_no_accesso_corso]="Nu esti autorizat sa accesezi acest curs";
$stringa[errore_no_login]="Trebuie sa te inregistrezi pentr a accesa acesta pagina";
$stringa[errore_no_tutor]="Trebuie sa fii tutorele macar al unui grup pentru a accesa aceasta pagina";

$stringa[nuovo_messaggio]="Mesaj nou";
$stringa[messaggio]="Mesaj";

$stringa[errore_no_intervento_del]="Postarea nu a fost gasita";
$stringa[errore_no_intervento_del_altro]="Iti poti sterge doar postarile tale";

$stringa[errore_file_rimosso]="Fisier sters sau deteriorat";

$stringa[ricevuto_replica]="Postarea ta a avut un raspuns in urmatorul forum";
$stringa[leggi_replica]="Poti citi postarea apasand click in linkul urmator, scris intr-o singura linie";

$stringa[messaggio_letto_da]="POSTARE CITITA DE:";

$stringa[istruzioni_chat]="Ghid Chat";
$stringa[faccine]="EmotIcons";
$stringa[non_verbali]="Expresii non-verbale";
$stringa[non_verbali_guida]="Incepand linia cu <b>+</b>, restul frazei nu va mai fi vizualizata <b>userul spune</b> ci doar <i><b>userul/b></i>. In acest fel poti comunica ceva ce faci (expresii nonverbale, posturi, emotii) si nu ceea ce spui. 
Spre exemplu, urmatoarea linie:<br> <b>+sare fercit!</b>, va fi aratata dupa cum urmeaza:<br><I><b>fleo</b> sare fericit!</i>";
$stringa[immagini_chat]="Inserare imagine";
$stringa[immagini_chat_guida]="Poti insera in linia ta o imagine uploadata. Ceea ce trebuie sa faci este sa scrii numele imaginii (fara extensii) intre asterixuri. <br><br>Spre exemplu, prin scierea urmatoarei linii:<br><br>Hi! Azi ma simt *bebelus3* ! <br><br>Imaginea denumita <I>bebelus3.gif</i> sau <i>bebelus3.jpg</i> (daca exista) va fi subistituita si aratata. Prin apasare click pe <b>Imagini Chat</b> poti obtine o lista de imagini uploadate si sa uploadezi altele noi din calculatorul tau ..";

$stringa[elenco_immagini_chat]="Lista de imagini uploadate";
$stringa[elenco_immagini_chat_guida]="Pentru a introduce o imagine in linia ta pune numele imaginii intre asterixuri sau apasa click pe <b>[Inserare]</b> <br>
Spre exemplu: <b>buna *bebelus3*</b>";
$stringa[carica_nuova_immagine]="Uploadeaza o imagine";
$stringa[clicca_vederla]="click pentru a mari...";

$stringa[errore_no_area]="Zona inexistenta";
$stringa[errore_no_parametri]="Logare invalida";
$stringa[errore_no_pagina]="Ne pare rau, pagina sau resursa indisponibila";
$stringa[errore_solo_staff]="Doar Staff-ul";
$stringa[errore_solo_admin]="doar Administratorii";
$stringa[errore_no_forum_disp]="Forum indisponibil";
$stringa[errore_no_forum_accesso]="Nu poti accesa acest forum";
$stringa[errore_no_risorsa_accesso]="Nu poti acesa aceasta pagina sau resursa";

$stringa[scegli_colore]="Alte culor...";

$stringa[esci]="Iesire";
$stringa[entra_stanza]="Intrare in camera";
$stringa[esce_stanza]="Iesire din camera";
$stringa[dice]="spune";

$stringa[annulla]="Renunta";
$stringa[selezionato]="selectat";
$stringa[colore_sfondo]="Culoare fundal";
$stringa[colore_sfondo_testata]="Culoare fundal a atetului";
$stringa[bordo]="Margine";
$stringa[altezza_cella]="Inaltime celula";
$stringa[larghezza_cella]="Latime celula";
$stringa[spazio_celle]="Spatiere celula";
$stringa[margine_interno]="Umplere celula";
$stringa[colonne]="Coloane";
$stringa[righe]="Randuri";

$stringa[utenti_attivi]="Activeaza userii din ultimile <b>10 minute</b>";
$stringa[aggiorna]="Update";
$stringa[ultima_attivita]="Ultima activitate";
$stringa[invita_chat]="Invita la chat";
$stringa[raggiungilo_chat]="alatura utilizator in camera de chat";
$stringa[staff]="Staff";

$stringa[errore_no_dato]="Ne pare rau, nu putem gasi nici un user in Kairos utilizand acele date.";
$stringa[caro]="Draga";
$stringa[ecco_parametri]="Aici aveti datele de locare pentru Kairos";
$stringa[scrivi_parametri]="Scrie datele exact asa cum sunt, avand grija la diferentele intre MAJUSCULE si minuscule.\nMerci!";
$stringa[amministratore_area]="Zona Administrator";
$stringa[pw_inviata]="OK, parola tocmai a fost trimisa la adresa ta de email.";
$stringa[parametri_accesso]="Date Logare";

$stringa[utente_invitato]="User invitat";
$stringa[utente_invitato_msg]="userul a fost invitat sa te alature .";
$stringa[chiude_da_sola]="Aceasta fereastra se va inchide in 5 secunde...";

$stringa[invito_chat]="Invitatie Chat";
$stringa[ricevuto_invito_chat]="Ai fost invitat intr-o camera pentru chat";
$stringa[da_p]="de la";
$stringa[declino]="Refuza";

$stringa[editor_collaborativo]="Editor Colaborativ";
$stringa[editor_finito]="Ai terminat de editat aceasta pagina. Ceilalti useri o pot schimba acum.";
$stringa[chiudi]="Inchide";
$stringa[replica]="Raspunde";

$stringa[messaggio_inviato]="Mesaj trimis.<br>Reincarcati pagina priata de email pentru a fi actualizata.";
$stringa[non_esiste]="nu exista";
$stringa[messaggio_inviato_fb]="Mesaj trimis";

$stringa[errore_manca_nome]="Nume lipsa";
$stringa[errore_manca_cognome]="Prenume lipsa";
$stringa[errore_manca_indirizzo]="Adresa lipsa";
$stringa[errore_manca_cap]="Cod postal lipsa";
$stringa[errore_manca_citta]="Oras lipsa";
$stringa[errore_manca_prov]="Judet lipsa";
$stringa[errore_manca_scuola]="Scoala lipsa";
$stringa[errore_manca_telefono]="Telefon lipsa";
$stringa[errore_manca_email]="E-Mail lipsa";
$stringa[errore_email_invalido]="E-Mail invalid";
$stringa[errore_manca_eta]="Varsta lipsa";
$stringa[errore_manca_sesso]="Sex lipsa";
$stringa[errore_email_esiste]="E-Mail deja utilizat";

$stringa[utente_si_e_registrato]="Urmatorul user s-a inregistrat in zona ta Kairos";
$stringa[conferma_registrazione_guida]="Pentru a accepta si confirma inregistrarea trebuie sa modifici registrul corespunzator al User Manager-ului din zona administrator.";
$stringa[richiesta_registrazione]="inregistrare necesara";
$stringa[grazie]="Multumim";
$stringa[richiesta_inoltrata]="Cererea de inregistrare a fost transmisa zonei administrator.<br>Parola va fi trimisa la adresa de email cand inregistrarea va fi confirmata.";
$stringa[benvenuto_demo]="Bun venit in zona demo din Kairos:\n
Aici introduceti datele de logare:";
$stringa[registrazione_demo]="Kairos inregistrare demo";
$stringa[parametri_inviati]="Parola va fi trimisa la adresa ta de email.";

$stringa[errore_manca_pw]="Parola lipsa";
$stringa[errore_solo_lettere_pw]="Doar litere, numere si _ pot fi folosite in parola";
$stringa[registrazione_man_fatta]="Inregistrare incheiata. Nu uitati sa informati userul despre datele sale de logare";

$stringa[errore_manca_testo]="Continut lipsa";

$stringa[errore_manca_oggetto_newsl]="Subiect lipsa";
$stringa[errore_manca_testo_newsl]="Continutul mesajului lipsa";

$stringa[anteprima_chat_collab]="Previzualizare chat colaborativ";
$stringa[errore_no_winie]="Ne pare rau, Microsoft Internet Explorer 5.0 or sau versiuni mai noi, Microsoft Windows 98 sau versiuni mai noi sunt necesare pentru a utiliza editorul colaborativ.";
$stringa[edit_comunque]="Editeaza oricum";
$stringa[file_in_uso]="Fisier utilizat de";
$stringa[anteprima_altra_finestra]="Previzualizeaza intr-o alta fereastra";

$stringa[indirizzo_file_suono]="URL-ul fisierului audio";
$stringa[indirizzo_file_suoni_guida]="URL-ul trebuie sa inceapa cu <b>http://...</b> si sa indice un fisier de tipul: <b>.wav</b>, <b>.mid</b>, <b>.au</b>, <b>.asf</b>";
$stringa[elenco_suoni]="Lista fisierelor audio uploadate";
$stringa[elenco_suoni_alt]="Deschide lista de fisiere audio pentru a alege unul sau pentru a uploada un altul.";

$stringa[indirizzo_file_flash]="URL-ul fisierului Flash";
$stringa[indirizzo_file_flash_guida]="URL-ul trebuie sa inceapa cu <b>http://...</b> si sa indice un fisier de tipul: <b>.swf</b>";
$stringa[elenco_flash]="Lista fisierelor Flash uploadate";
$stringa[elenco_flash_alt]="Deschide lista de fisiere Flash pentru a alege unul sau pentru a uploada un altul.";
$stringa[larghezza]="Latime";
$stringa[altezza]="Inaltime";

$stringa[indirizzo_file_video]="URL-ul fisierului video";
$stringa[indirizzo_file_video_guida]="URL-ul trebuie sa inceapa cu <b>http://...</b> si sa indice un fisier de tipul: <b>.mpg</b>, <b>.avi</b>, <b>.mov</b>";
$stringa[elenco_video_alt]="Deschide lista de fisiere video pentru a alege unul sau pentru a uploada un altul.";
$stringa[elenco_video]="Lista fisierelor video uploadate ('wmv','mov','rpm', 'ogg', 'mp4' max 10 M)";

$stringa[utente_modificato]="Profilul userului modificat.";
$stringa[errore_esiste_domanda_allegato]="Exista deja o intrebare despre atasarea tipului de fisier.";

$stringa[guarda_sito]="Vizualizeaza site-ul tau";
$stringa[istruzioni]="Instructiuni";
$stringa[archivio_zip]="Uploadeaza fisier .zip";

$stringa[salva_file]="Salveaza fisier";
$stringa[salva_file_in]="Salveaza fisier in...";
$stringa[salva]="Salveaza";
$stringa[pagina_salvata]="Fisierul a fost salvat utilizand urmatorul URL";
$stringa[apri_file_selezionato]="Deschide fisierul selectat";
$stringa[apri_file]="Deschide fisier";

$stringa[file_gif_testata]="Header imagine prim plan(.gif/.jpg):";
$stringa[file_gif_test_guida]="marime permisa: exact 78 pixels inaltime - max 756 pixel latime.";
$stringa[reimposta_default]="reseteaza la prestabilite";
$stringa[file_gif_sfondo]="Header imagine fundal (.gif/.jpg):";
$stringa[file_gif_sfondo_guida]="marile permisa: 78 x 800 pixel";
$stringa[colore_testo]="Text:";
$stringa[colore_sfondo]="Fundal:";
$stringa[colore_bordi]="Margine:";
$stringa[colore_testo_negativo]="Text inversat:";
$stringa[colore_link]="Link:";
$stringa[str1]="Text pe fundal alb";
$stringa[str2]="Text inversat";
$stringa[str3]="Text bold mic";
$stringa[str4]="Text simplu";

$stringa[errore_immagine_gif_testata]="Imaginea fundalului header-ului trebuie sa fie .gif";
$stringa[errore_testata_max]="Latimea imaginii header-ului in prim-plan trebuie sa fie de max. 756 pixels";
$stringa[errore_testata_78]="Inaltimea imaginii header-ului in prim-plan trebuie sa fie de exact 78 pixels";

$stringa[errore_immagine_gif_sfondo]="Imaginea fundalului header-ului trebuie sa fie .gif";
$stringa[errore_sfondo_800]="Latimea imaginii header-ului in fundal trebuie sa fie de exact 800 pixels";
$stringa[errore_sfondo_78]="Inaltimea imaginii header-ului in fundal trebuie sa fie de exact 78 pixels";

$stringa[num_domande_random]="Numarul intrebarilor random";
$stringa[punteggio_soglia]="Minimul de scor pentru a considera testul trecut";
$stringa[test_superato]="Test trecut";
$stringa[test_non_superato]="Test picat";

$stringa[iscriviti_corsi]="Selecteaza cursul la care vrei sa te inscrii";

$stringa[utente_tutor]="User este tutor al urmatoarelor grupuri";
$stringa[utente_corsi_attivi]="Userul s-a inscris la urmatoarele cursuri";

$stringa[contenuto_cartella]="Continutul folderului";
$stringa[collega_pagine]="Introdu in folder legaturile la paginile selectate";
$stringa[repertorio_pagine]="Paginile web depozitate sunt corelate in folderul";

$stringa[download]="Download";

$stringa[database_lavori]="Portofoliu User";
$stringa[principale]="sursa";
$stringa[nuovo_sito_web]="Web site nou";
$stringa[sito_web]="Web site";

$stringa[chi_scaricato]="Cine l-a downloadat?";
$stringa[chi_visto]="Cine l-a vizualizat?";
$stringa[commenti]="Comentarii & Feedback";
$stringa[commenti_aggiungi]="Adauga un comentariu";
$stringa[scrivi_commento]="Scrie comentariul sau un feedback";

$stringa[cerca_in]="Cauta in";
$stringa[tutti_corsi]="toate cursurile";
$stringa[solo_corso]="doar in cursurile selectate";
$stringa[utenti]="Useri";
$stringa[del_corso]="Continuturi curs";
$stringa[degli_utenti]="Continuturile userului";
$stringa[cerca_materiali]="Cauta continuturi";


$stringa[bacheca]="WebBoard";
$stringa[postit]="Posteaza";
$stringa[mostra_nascondi]="Arata/Ascunde";
$stringa[mostra]="Arata";
$stringa[nascondi]="Ascunde";
$stringa[nuovo_p]="Nou";

$stringa[chiama_helpdesk]="Pentru asistenta in utilizarea acestui site suna la <b>+39 064882110</b> sau scrie la: <a href=mailto:supporto@garamond.it><b>supporto@garamond.it</b></a>";

$stringa[gestione_staff]="Gestiune Staff";
$stringa[staff_direttore]="Director";
$stringa[staff_coordinatore]="Tutor responsabil";
$stringa[staff_docente]="Profesori";
$stringa[staff_esperto]="Experti";
$stringa[staff_tutor]="Tutor";
$stringa[staff_autore]="Autori";
$stringa[aggiungi_staff]="Adauga utilizator al staff-ului";

$stringa[errore_no_utente]="Utilizator inexistent";

$stringa[invio_newsletter_globale]="Trimite Newsletter global";
$stringa[invio_newsletter_globale_label]="Mesajul este transmis tuturor utilizatorilor Kairos.";
$stringa[invio_newsletter_label]="Mesajul este transmis doar la abonatii din cursul selectat.";

$stringa[appunti]="Note";
$stringa[messaggio_inviato]="Mesaj trimis.";
$stringa[segna_come_letti]="Marcheaza toate ca fiind citite";

$stringa[annulla_setcorso]="Deselecteaza";
$stringa[annulla_setcorso_tip]="Deselecteaza context curs";

$stringa[esporta_iscritti]="Exporta lista";
$stringa[project_work]="Portfoliu WEB";

$stringa[ruolo_scuola]="Rolul Scolii";
$stringa[materia_insegnata]="Subiect de invatare";
$stringa[guida_materia_insegnata]="necesara in cazul in care ati selectat rolul de: \"Profesor\"";
$stringa[dirigente]="Director";
$stringa[insegnante]="Profesor";
$stringa[studente]="Elev";
$stringa[nessun_ruolo]="Nu lucrez in scoala";

$stringa[errore_manca_materia]="Subiect de invatare ratat";

$stringa[autoiscrizione]="Auto-inregistrare activata";
$stringa[conf_canc]="Esti sigur ca vrei sa-l stergi?";

$stringa[gestione_iscrizioni]="Inscrieri la curs";
$stringa[cerca_registrati]="Cauta userii care vrei sa se inscrie la curs";
$stringa[data_registrazione]="Data inregistrarii";
$stringa[cerca_iscritti]="Cauta userii care s-au inscris la cursul pe care tu vrei sa-l stergi sau sa-l muti";
$stringa[data_iscrizione]="Data inscrierii";
$stringa[cancella_iscrizione]="Sterge inscriere";
$stringa[iscrizioni_trovate]="Inscrieri gasite";
$stringa[iscrivi_utenti_selezionati]="Inscrie userii selectati la urmatoarele cursuri";
$stringa[sposta_iscrizioni_selezionate]="Muta inscrierile selectate la urmatoarele cursuri";

$stringa[materiali_copia]="Copiere resurse de la un curs la altul";
$stringa[corso_da_copiare]="Originea cursului";
$stringa[corso_su_copiare]="Originea destinatiei";

$stringa[report_corso]="Raportul final al cursului";
$stringa[livello_competenze]="Nivel atins";
$stringa[superato_corso]="Degreed Flag";

$stringa[seleziona_edizione]="selecteaza editie";
$stringa[mia_cartella]="Portfoliul meu";
$stringa[cartella_utente]="Portfoliu";

$stringa[stat_ok]="OK";
$stringa[stat_processing]="proceseaza";
$stringa[stat_wait]="asteapta";

$stringa[stat_msg]="Cererea ta va fi procesata cat se poate de repede (aprx. intre 30-60 minutes). <br>
Un mesaj va fi transmis pe adrea de email cand va fi gata.<br>
Verifica starea cererii tale la pagina <b>Statistici</b> .
<br>
Multumim.";

$stringa[max_7_giorni]="Perioada de timp trebuie sa includa max. <b>7 zile</b>";
$stringa[max_30_giorni]="Perioada de timp trebuie sa includa  max. <b>31 zile</b>";

$stringa[tutti]="Arata tot";
$stringa[invia_staff]="Trimite o copie carte staff";

$stringa[editor_gruppi]="Editor grupuri";
$stringa[editor_attesa]="Staff useri pe care ii poti adauga grupului";
$stringa[editor_iscritti]="Staff useri adaugati la grup ";

$stringa[aggiungi_commento]="Adauga un comentariu la aceasta pagina";
$stringa[btn_aggiungi_commento]="Adauga comentariu";
$stringa[lettore]="User";
$stringa[commenti_lettori]="Comentarii useri";

$stringa[gestione_contenuti]="Manager de continut";
$stringa[utility]="Utilitati";
$stringa[gestione_edizioni]="Edition Manager";
$stringa[edizioni]="#Editions";
$stringa[iscrizione_utenti]="Inscrieri useri la curs";
$stringa[gestione_gruppi]="Manager grup";
$stringa[gestione_forum_comuni]="Manager forum comun";
$stringa[iscrivi_utenti_selezionati]="Inscrie userii selectati la curs";
$stringa[utenti_modifica]="Modifica/Sterge useri inregistrati";

$stringa[news_forum_comuni]="Stiri de la forumuri comune";
$stringa[news_forum_corso]="Stiri de la forumurile cursului";
$stringa[news_forum_gruppo]="Stiri de la forumul grupului";
$stringa[news_forum_gruppo_pw]="Stiri de la forumul prectului de lucru";
$stringa[news_forum_gruppo_tutor]="Stiri de la forumul grupului unde esti tutore";
$stringa[news_eventi]="Evenimente recente si viitoare din calendar";
$stringa[news_portfolio]="Cele mai recente contributii in portofoliul userului";

$stringa[new_post]="postari noi";
$stringa[utilities]="Utilitati";
$stringa[visualizzazione]="Vizualizeaza";
$stringa[struttura_intervento]="Thread";
$stringa[cartelle]="FOLDER";
$stringa[iscriviti]="Inscriete la acest curs";
$stringa[iscrizione_fatta]="Inscrierea la curs a fost efectuata.";
$stringa[iscrizione_fatta_edizione_attiva]="Puteti frecventa editia actualmente activa";
$stringa[iscrizione_fatta_edizione_inattiva]="Va trebui sa asteptati comunicarea de la tutore pentru a incepe editia cursului la care ati fost inscris";

$stringa[url]="URL";
$stringa[posizione_news]="Pozitia stirii";
$stringa[errore_posizione_news]="Nu ai indicat pozitia strii";

$stringa[gruppo_0]="Clasa";
$stringa[gruppo_1]="Proiectul";

$stringa[creato]="creat";
$stringa[modificato]="modificata";
$stringa[materiale_storia]="Istoricul operatiunii obiectului";
$stringa[lavori_gruppo]="Grupuri de lucur";
$stringa[componenti_gruppo]="Membri gruplui";

$stringa[forum_mail_on]="Notificare in adresa de email cand apar postari noi in acest forum";
$stringa[forum_mail_off]="Opreste notificarile la postarile noi in acest forum";

$stringa[forum_scritto_post]="O noua postare a fost scrisa in acest forum";

$stringa["materiali_corso"]="Resursele cursului";
$stringa["materiali_comuni"]="Resurse comune";
$stringa["materiali_gruppo"]="Resurse de grup";
$stringa[nome_organizzazione]="Organizare";

$stringa[seleziona_tutti]="Selecteaza tot";
$stringa[deseleziona]="Deselecteaza";

$stringa[gestione_repository]="LO Repository";
$stringa[nuovo_lo]="LO Nou";
$stringa[lo]="LO";
$stringa[lo_tema_grafico]="Tema grafica";
$stringa[lo_tipo]="LO tip";
$stringa[cartella_sup]="In folder";
$stringa[nuovo_quiz]="Noua Evaluare";
$stringa[conf_cancella_verifica]="Esti sigur ca vrei sa stergi aceasta evaluare?";
$stringa[importa_lo]="Importa LO";

$stringa[materia]="Subiect";
$stringa[argomenti]="Topicuri";
$stringa[obiettivi_didattici]="Obiective de invatare";
$stringa[fruitore]="EndUser profile";
$stringa[competenze_ingresso]="Cerinte preliminare";

$stringa[titolo_lo_autore]="LO titlu si autor";
$stringa[azioni]="Actiuni";
$stringa[lancia_lo]="LO Previzualizare";
$stringa[traccia_lo]="LO Urmareste";

$stringa[solo_testo]="Doar Text";
$stringa[testo_immagine]="Text si Imagine";
$stringa[testo_video]="Text si video";
$stringa[testo_flash]="Text si animatie Flash";
$stringa[solo_immagine]="Doar Imagine";
$stringa[solo_video]="Doar Video";
$stringa[solo_flash]="Doar animatie Flash";
$stringa[approfondimento]="pop-up pagina";
$stringa[template]="Sablon";

$stringa[audio_opzionale]="Fisier audio optional";
$stringa[audio]="Fisier Audio";
$stringa[img]="Fisier Imagine";
$stringa[video]="Fisier Video";
$stringa[flash]="Fisier Flash";

$stringa[posizione_relativa]="Aspect Pagina";
$stringa[colonna_destra_multiplo]="Unul sau mai multe obiecte in coloana din dreapta";
$stringa[colonna_sinistra_multiplo]="Unul sau mai multe obiecte in coloana din stanga";
$stringa[testo_destra]="Obiect in dreapta";
$stringa[testo_sinistra]="Obiect in stanga";
$stringa[colonna_destra]="Obiect in coloana din dreapta";
$stringa[colonna_sinistra]="Object in coloana din stanga";
$stringa[colonna_grande_destra]="Obiect mare in coloana din dreapta";
$stringa[colonna_grande_sinistra]="Obiect mare in coloana din stanga";
$stringa[sopra]="Obiect sus";
$stringa[sotto]="Object jos";
$stringa[alt_text]="Text alternativ";

$stringa[alt_text]="Text alternatic";
$stringa[aggiungi_immagine]="Adauga imagine";
$stringa[elimina_immagine]="Sterge";
$stringa[lo_tipo_lom]="LO tip";
$stringa[esempio]="Example";
$stringa[alt_img]="Imagine Alternativa";

$stringa[questionari_corso]="Chestionar";
$stringa[riepilogo]="&Aratati rezultatul final";
$stringa[lo_pubblicazione]="Atribuirea cursului LO";
$stringa[lo_non_pubblicati]="Rezultate cautare LO (care urmeaza sa fie alocate)";
$stringa[lo_pubblicati]="Curs LO atribuit";
$stringa[lo_corso]="LO al cursului";
$stringa[lo_dafare]="LO de completat";
$stringa[lo_fruizione]="Stato fruizione LO del corso";
$stringa[lo_f]="Fruizione";

$stringa[link_tutoriale_alternativo]="Pagina alternativa";
$stringa[link_tutoriale_ref]="Pagina tutoriale centrale";
$stringa[pag_glossario]="&Marcheaza pagina glosar";
$stringa[commento]="Comentariu Utilizator";

$stringa[lo_modocontinua]="Permite reinceperea procesului dupa inchidere";
$stringa[lo_bloccoavanzamento]="Blocheaza progresele inregistrate la pagina de test";
$stringa[testo_geogebra]="GeoGebra";
$stringa[elenco_geogebra]="Lista de fisiere GeoGebra incarcate/Reincepe incarcare altui fisier GeoGebra";
$stringa[ggb]="File ggb";

$stringa[it] = "Italiano";

$stringa[en] = "English";
$stringa[ro] = "Romana";
$stringa[us] = "English US";
$stringa[uk] = "English UK";

$stringa[registration_required0] = "Pentru ID si PW e <br>necesara ";
$stringa[registration_required1] = "inregistrarea";
$stringa[lo_viewer_Prerequisiti] = "Cunostinte necesare";
$stringa[lo_viewer_Obbietivi] = "Obiective";
$stringa[lo_viewer_Argomenti] = "Subiecte";
$stringa[lo_viewer_Materia] = "Materie";
$stringa[lo_viewer_lo_tipo] = "Tipul Lectiei";
$stringa[aula_virtuale] = "Clasa Virtuala";
$stringa[Repository] = "Repository";
$stringa[tools] = "Setari";
$stringa[lo_test_add_opzione] = "Pentru a introduce opziuni delimitati raspunsurile folosind  ; cu 0 pentru fals si 1 pentru adevarat. <br/><strong>Ex.</strong> Culoarea cerului?<br/>galbena:0;<br/>verde:0;<br/>albastra:1;</span>";

$stringa[consegna] = "Prezentare pana la";
$stringa[msg_ok_content] = "Raspuns exact! Inainte";
$stringa[msg_ko_content] = "Gresit! Studiaza!!";
$stringa[sm_rs] ="SMRS";
$stringa[sm_rm] ="sm_rm";
$stringa[dragdrop] ="Drag Drop";
$stringa[cacciaerrore] = "Gaseste greseala";
$stringa[ascoltaescrivi] = "Asculta si scrie";
$stringa[cruciverba] = "Completeaza restul";
$stringa[guest_welcome] = "Bine ai venit!"
?>

