<?php
$nomemese["January"]="January";
$nomemese["February"]="February";
$nomemese["March"]="March";
$nomemese["April"]="April";
$nomemese["May"]="May";
$nomemese["June"]="June";
$nomemese["July"]="July";
$nomemese["August"]="August";
$nomemese["September"]="September";
$nomemese["October"]="October";
$nomemese["November"]="November";
$nomemese["December"]="December";

$stringa[home]="Home";
$stringa[forum]="Forum";
$stringa[chat]="Chat";
$stringa[chi_e_in_linea]="Who's on line";
$stringa[posta_interna]="Mail";
$stringa[eventi]="Calendar";
$stringa[materiali]="Content";
$stringa[materiali_test]="Content & Test";
$stringa[laboratori]="Laboratory";
$stringa[cerca]="Search";
$stringa[info]="Info";
$stringa[catalogo_corsi]="Course Catalogue";
$stringa[helpdesk]="Helpdesk";
$stringa[admin]="Admin";
$stringa[buon_lavoro]="Welcome";
$stringa[modifica_profilo]="Change your password and other personal data";
$stringa[statistiche]="Statistics";
$stringa[statistiche_alt]="Statistics about your course usings";
$stringa[logout_alt]="Exit from Kairos";
$stringa[logout]="X";
/* -------- */

$stringa[gruppo]="Group";
$stringa[tutor]="Tutor";
$stringa[clicca_per_sapere_chi]="Click to figure out who he/she is...";

$stringa[ricevuto_invito]="You have been invited for a chat in the room";
$stringa[accetto]="Accept";

$stringa[nuovi_messaggi]="You have new messages into the";

$stringa[sito_realizzato]="Powered by";
$stringa[piattaforma_per]="e-learning platform";

$stringa[generale]="General";
$stringa[laboratorio]="Laboratory";

$stringa[su_max]="out of";

$stringa[pagina_up]="Move up";
$stringa[pagina_down]="Move down";
$stringa[cancella]="Delete";
$stringa[modifica]="Modify";
$stringa[modifica_file]="Modify File";
$stringa[modifica_pagina]="Modify web page";
$stringa[modifica_sito]="Modify web site";
$stringa[pagina_web]="Web page";
$stringa[nota]="Note";
$stringa[file]="File";
$stringa[apri_cartella]="Open folder";
$stringa[dir_superiore]="Folder up";
$stringa[inserisci]="Insert";
$stringa[copia_indirizzo]="Copy";

$stringa[nuovo]="New!";
$stringa[nuovo_interno]="News inside!";

$stringa[inserisci_tabella]="Insert Table";
$stringa[inserisci_immagine]="Insert Image";
$stringa[inserisci_suono]="Insert Sound";
$stringa[inserisci_flash]="Insert Flash animation";
$stringa[inserisci_video]="Insert Video";
$stringa[crea_link]="Create Link";
$stringa[indentato]="Indent";
$stringa[non_indentato]="Outdent";
$stringa[elenco_numerato]="Ordered list";
$stringa[elenco]="Unordered list";
$stringa[allineato_dx]="Align right";
$stringa[allineato_centro]="Align center";
$stringa[allineato_sx]="Align left";
$stringa[corsivo]="Italic";
$stringa[sottolineato]="Underline";
$stringa[grassetto]="Bold";
$stringa[redo]="Redo";
$stringa[undo]="Undo";
$stringa[incolla]="Paste";
$stringa[copia]="Copy";
$stringa[taglia]="Cut";
$stringa[testo]="TEXT";

$stringa[mod_testo]="You have to set TEXT mode";

$stringa[login]="LOGIN";
$stringa[id]="ID";
$stringa[pw]="PW";
$stringa[dimenticato_pw]="I've forgotten my password!";
$stringa[login_atlante]="You need first to <b>login</b> into";

$stringa[indietro]="Back";
$stringa[avanti]="Forward";

$stringa[area_admin]="Administration Area";
$stringa[gestione_forum]="Forum Manager";
$stringa[invio_newsletter]="Send Course Newsletter";
$stringa[statistiche_corso]="Course Statistics";
$stringa[monitoraggio_corso]="Course Monitoring";
$stringa[gestione_materiali]="Content Manager";
$stringa[personalizza_interfaccia]="Customize Layout";
$stringa[gestione_utenti]="User Manager";
$stringa[gestione_corsi]="Course Manager";
$stringa[nuova_pagina_web]="New web page";
$stringa[nuovo_file]="New file";
$stringa[nuova_cartella]="New folder";

$stringa[calendario_eventi]="Events Calendar";
$stringa[nuovo_evento]="New Event";
$stringa[lunedi]="Monday";
$stringa[martedi]="Tuesday";
$stringa[mercoledi]="Wednesday";
$stringa[giovedi]="Thursday";
$stringa[venerdi]="Friday";
$stringa[sabato]="Saturday";
$stringa[domenica]="Sunday";
$stringa[seleziona]="Select";
$stringa[no_selezione]="No selected event to delete.";
$stringa[evento_cancellato]="Event deleted.";
$stringa[no_modifica]="No selected event to modify.";

$stringa[gestione_cartella_img]="IMG Folder Manager";
$stringa[cancella_elementi]="Delete selected items";

$stringa[cerca_utenti]="Search user";
$stringa[identificativo]="User ID";
$stringa[nome]="Name";
$stringa[cognome]="Surname";
$stringa[prov]="Prov.";
$stringa[citta]="City";

$stringa[cerca_forum]="Search forum";
$stringa[inserisci_stringa]="Please insert at least a word to search.";
$stringa[non_trovato]="Nothing found";
$stringa[pagine]="Pages";
$stringa[cerca_risultati]="Search results";
$stringa[num]="N.";
$stringa[utente]="User";
$stringa[manda_messaggio]="send a private message to the user";

$stringa[chat]="Chat";
$stringa[chat_intro]="To enter, click on the room's name.<br>The number in brackets shows how many users are chatting in that room at this moment.";
$stringa[Generale]="General";
$stringa[laboratorio]="Laboratory";
$stringa[archivio_chat]="Chat Archive";

$stringa[hai_dimenticato_pw]="Have you forgotten your password?";
$stringa[nessun_problema]="No problem. Just type in your email or User ID. You'll get the password immediately to your email.";
$stringa[email_id]="Email or User ID";

$stringa[nuovo_forum]="New Forum";
$stringa[id_forum]="Forum ID";
$stringa[posizione]="Order";
$stringa[indica_posizione]="type in a number corresponding to the position in which you want to put the forum in the ordered list of defined fora.";
$stringa[descrizione]="Description";
$stringa[tipo]="Type";
$stringa[corso]="Course";
$stringa[staff]="Staff";
$stringa[file_allegati]="File attaching";
$stringa[si]="Yes";
$stringa[no]="No";
$stringa[crea]="CREATE";

$stringa[tempo]="Time";
$stringa[oggetto]="Subject";

$stringa[modifica_forum]="Modify Forum";
$stringa[qualunque]="any";

$stringa[cartella]="Folder";
$stringa[id_file]="File ID";
$stringa[file_caricare]="File to upload";
$stringa[livello]="Level";
$stringa[pubblico]="Public";
$stringa[registrati]="Registered";
$stringa[parole_chiave]="Keywords";
$stringa[carica]="UPLOAD";

$stringa[id_cartella]="Folder ID";

$stringa[stanza]="Room";
$stringa[giorno]="Day";
$stringa[dalle_ore]="From";
$stringa[alle_ore]="To";
$stringa[ok]="OK";

$stringa[pos]="Pos.";
$stringa[num_int]="#Posts";

$stringa[modifica_intervento]="Modify Post";
$stringa[autore]="Author";
$stringa[intervento]="Post";
$stringa[allega_file]="Attach file (max. 5MB)";
$stringa[file_allegato]="File attached";
$stringa[cancella_allegato]="delete attached file";
$stringa[icona]="Icon";
$stringa[generica]="neutral";
$stringa[domanda]="question";
$stringa[idea]="idea";
$stringa[approvo]="agree";
$stringa[disapprovo]="disagree";
$stringa[importante]="important";
$stringa[confuso]="confused";
$stringa[contento]="happy";
$stringa[triste]="sad";
$stringa[scherzo]="joke";
$stringa[arrabbiato]="angry";
$stringa[moltoarrabbiato]="veryangry";
$stringa[fico]="cool";
$stringa[invia_repliche]="Send replies to my email too";

$stringa[web_forum]="Forum";
$stringa[cerca_forum]="Search in forums";
$stringa[cerca]="Search";
$stringa[risultati_5]="5 results per page";
$stringa[risultati_10]="10 results per page";
$stringa[risultati_20]="20 results per page";
$stringa[risultati_30]="30 results per page";
$stringa[risultati_50]="50 results per page";
$stringa[archivio_faq]="Answers to the most frequent course questions archive";
$stringa[faq]="FAQ";
$stringa[forum_intro]="To enter, click on the name of the forum.
In brackets are shown the number of posts, and any that you have not yet read.
<br>";
$stringa[forum_staff]="Staff forums";
$stringa[forum_generali]="General forums of the platform";
$stringa[forum_corso]="Course forums";
$stringa[forum_gruppo]="Forums of your group";
$stringa[forum_del_gruppo]="Forums of the group";
$stringa[forum_del_gruppo_pw]="Forums of the Project Work group"; 

$stringa[nuovo_intervento]="New post";
$stringa[comprimi_struttura]="Close all threads";
$stringa[espandi_struttura]="Collapse all threads";
$stringa[vista_cronologica]="View by date";
$stringa[vista_struttura]="View by threads";
$stringa[interessanti]="View by marked";

$stringa[prec]="Previous";
$stringa[succ]="Next";
$stringa[intervento_sup]="Up to thread";
$stringa[indice]="Index";
$stringa[replica_intervento]="Reply post";
$stringa[modifica_intervento]="Modify post";
$stringa[cancella_intervento]="Delete post";
$stringa[interessante]="Mark post";
$stringa[non_interessante]="Unmark post";
$stringa[chi_letto_alt]="Click to see who has read the post";
$stringa[chi_letto]="Who read it?";
$stringa[da_leggere]="Unread";
$stringa[ricopia_faq]="Copy to FAQ";
$stringa[sposta_in]="Move to";
$stringa[sposta]="Move";
$stringa[ha_scritto]="wrote";
$stringa[senza_oggetto]="no subject";
$stringa[senza_titolo]="no title";

$stringa[avere_id]="To get an ID and PW<br>you have to";
$stringa[registrarsi]="register";
$stringa[corsi]="Course Editions";
$stringa[news_direzione]="News";
$stringa[nuova_news]="New";
$stringa[no_primo_piano]="No more at the top";
$stringa[news_iscritti]="User space";
$stringa[modifica_sezione]="Edit this section, posting  all the news that you think would be of interest for the community.";

$stringa[spazio_web_pers]="Personal web space";
$stringa[cartelle_condivise]="Shared web space";
$stringa[chat_collaborativo]="Collaborative chat";
$stringa[lavori_corsisti]="Users' project works list";
$stringa[corsista]="User";
$stringa[sito]="Site";

$stringa[cartella_file]="File folder";

$stringa[conf_cancella_pagina]="are you sure you want to delete this web page and all its aliases?";
$stringa[conf_cancella_lab_sito]="are you sure you want to delete the reference to this web site?";
$stringa[conf_cancella_file]="are you sure you want to delete this file?";
$stringa[conf_cancella_cartella]="are you sure you want to delete this folder and all its content?";
$stringa[conf_cancella_nota]="are you sure you want to delete this note?";
$stringa[conf_cancella_link]="are you sure you want to delete this alias?";

$stringa[gestione_test]="Test manager";
$stringa[sequenza_pubblicazione]="Course content assignment";
$stringa[sequenza_pubblicazione_comune]="Common area content assignment";

$stringa[id_pagina_web]="Page ID";
$stringa[normale]="Normal";
$stringa[titolo]="Title";
$stringa[codice_contenuto]="HTML content code";
$stringa[contenuto]="Content";

$stringa[inviati]="sent";
$stringa[ricevuti]="received";
$stringa[messaggi]="Messages";
$stringa[nuovo_messaggio_alt]="new message";
$stringa[nuovo_messaggio]="Write a new message";
$stringa[da]="From";
$stringa[a]="To";
$stringa[spedito]="Sent";
$stringa[letto]="Read";
$stringa[leggi_messaggio_alt]="open the message";

$stringa[modifica_profilo]="Modify user profile";
$stringa[modifica_intro]="";
$stringa[immagine_profilo]="Image (GIF/JPG max 100KB)";
$stringa[immagine_profilo_alt]="click to see the uploaded image";
$stringa[immagine]="Image";
$stringa[password]="Password";
$stringa[indirizzo]="Address";
$stringa[cap]="ZIP";
$stringa[scuola]="School";
$stringa[telefono]="Telephone";
$stringa[email]="E-Mail";
$stringa[sitoweb]="Web Site";
$stringa[sesso]="Gender";
$stringa[m]="M";
$stringa[f]="F";
$stringa[eta]="Age";
$stringa[interessi]="Interests";
$stringa[qualcosa_di_me]="Something about me";

$stringa[stanza_di_chat]="Chat room";
$stringa[dialoghi_del]="Chat of";
$stringa[totale_righe]="Total rows";
$stringa[totale_utenti]="Total users";
$stringa[utente]="User";
$stringa[righe]="Rows";
$stringa[entra_esce]="enter/exit";

$stringa[crea_news]="Create News";
$stringa[primo_piano]="Top news";
$stringa[news]="News";
$stringa[facoltativo]="optional";
$stringa[testo]="Content";
$stringa[modifica_news]="Modify News";

$stringa[giorno]="Day";
$stringa[evento_confermato]="Event confirmed.";
$stringa[torna_mese]="Back to month";

$stringa[registrazione]="Registration";
$stringa[stato]="Role";
$stringa[id_guida]="(letter and/or number only without spaces)";
$stringa[registrazione_guida]="Your registration will be confirmed by the <b>area administrator</b>.";
$stringa[modifica_ruolo]="Change role to selected users";
$stringa[registrazione_manuale]="New platform user registration";
$stringa[registrazion_man_guida]="The registration will be activated immediately. You have to inform the user about his/her ID and PW.";

$stringa[registrato_attesa]="registered waiting";
$stringa[id_utente]="User ID";
$stringa[utenti_trovati]="Users found";
$stringa[nuova_ricerca]="New search";

$stringa[test]="Test";
$stringa[duplica]="Copy";
$stringa[nuovo_test]="New test";
$stringa[domande]="Questions";
$stringa[duplica_test]="Copy test";
$stringa[test_modifica]="Modify test";
$stringa[id_test]="Test ID";
$stringa[verifica]="verify";
$stringa[sondaggio]="survey";
$stringa[num_comp]="#Filled";
$stringa[risultati]="Results";
$stringa[edit]="Edit";
$stringa[edit_test]="Edit test";
$stringa[aggiungi_domanda]="Add question";

$stringa[nuova_domanda_test]="New question of test";
$stringa[chiusa]="Multiple choices";
$stringa[risposta_multipla]="Multiple answers";
$stringa[vero_falso]="True/False";
$stringa[inserimento]="Fill-the-blank";
$stringa[associazione]="Match";
$stringa[aree_immagine]="Image areas";
$stringa[aperta]="short answer";
$stringa[scelta]="Option";
$stringa[punteggio]="Score";
$stringa[chiedi_altro]="Ask Other to specify";
$stringa[commento_post]="Feedback";

$stringa[modifica_domanda_test]="Modify question of test";

$stringa[conferma_del_test]="are you sure you want to delete the test and all its fillings?"; 

$stringa[compilazione_test]="Fill in the test";
$stringa[test_inesistente]="Test does not exist.";
$stringa[altro_specificare]="Other, please specify";

$stringa[risposta_fornita]="Your answer was";
$stringa[risposte_possibili]="Possible answers (corresponding score)";
$stringa[note]="Note";
$stringa[punteggio_ottenuto]="You got the following score";
$stringa[punteggio_max]="out of";
$stringa[questionario_registrato]="The survey has been registered. Thank you!";

$stringa[risultati_test]="Results of test";
$stringa[data_prima]="First filling date";
$stringa[data_ultima]="Last filling date";
$stringa[tot_compilazioni]="Total fillings";
$stringa[risposte_aperte]="Open answers";
$stringa[altro]="Other";
$stringa[non_risposto]="Not answered";

$stringa[elenco_compilazioni]="List fillings of test";
$stringa[data]="Date";
$stringa[questionario_compilato]="Filled test";

$stringa[no_file]="no file";
$stringa[dettaglio_risposta]="Answers to the question";

$stringa[web]="Web";
$stringa[file]="File";
$stringa[link]="Link";
$stringa[materiali_non_pubblicati]="Content not assigned to the course";
$stringa[materiali_pubblicati]="Content assigned to the course";
$stringa[materiali_non_pubblicati_comune]="Content not assigned to the common area";
$stringa[materiali_pubblicati_comune]="Content assigned to the common area";

$stringa[nuovo_corso]="New Course";
$stringa[edizione]="Edition";
$stringa[iscritti]="#Subscribed";
$stringa[status]="State";
$stringa[nuova_edizione]="New Edition";

$stringa[id_corso]="Course ID";
$stringa[nuova_edizione_corso]="New course edition";
$stringa[id_edizione]="Edition ID";
$stringa[data_inizio]="Starting date";
$stringa[durata]="Duration";
$stringa[mesi]="months";
$stringa[giorni]="days";
$stringa[attiva]="active";
$stringa[inattiva]="unactive";

$stringa[modifica_corso]="Modify Course";
$stringa[modifica_edizione_corso]="Modify Course Edition";

$stringa[iscrizioni_effettuate]="He/she subscribed to the following courses";
$stringa[gestione_iscrizioni]="Course subscription manager";
$stringa[nuovo_gruppo]="New Group";
$stringa[id_gruppo]="Group ID";
$stringa[id_tutor]="Tutor ID";
$stringa[opzionale]="optional";
$stringa[modifica_gruppo]="Modify group";

$stringa[gestione_gruppo]="Group manager";
$stringa[utenti_attesa]="Users don't assigned to the group";
$stringa[utenti_iscritti]="Users assigned to the group";
$stringa[utenti_attesa_pw]="Users assignable to the project work";
$stringa[utenti_iscritti_pw]="Users already assigned to the project work";

$stringa[statistiche_corso]="Course statistics";
$stringa[dal]="From";
$stringa[al]="To";
$stringa[sessioni]="Sessions";
$stringa[interventi_forum]="Forum posts";
$stringa[durata_media]="Average time";
$stringa[durata_totale]="Total time";
$stringa[scritti]="Written";
$stringa[letti]="Read";
$stringa[righe_chat]="Chat rows";
$stringa[risorse_piattaforma]="Platform resources";

$stringa[no_privilegi]="You cannot access to this resource.";
$stringa[no_accesso]="You cannot access to this content.";
$stringa[dettaglio_statistiche]="Course statistics details";
$stringa[interventi_scritti]="Written forum posts";
$stringa[interventi_letti]="Read forum posts";

$stringa[ricopia_in_faq_corso]="Copy post to course FAQ";
$stringa[domanda_f]="Question";
$stringa[risposta_f]="Answer";

$stringa[modifica_faq_corso]="Modify course FAQ";
$stringa[faq_corso]="Course FAQ";
$stringa[nuova_faq]="New";

$stringa[errore_gif_jpg]="Only gif or jpg file allowed.";
$stringa[errore_max_file]="File size too big.";
$stringa[errore]="Error";
$stringa[errore_intro]="Sorry, I got the following errors";
$stringa[errore_file_esiste]="File already exists.";

$stringa[errore_forum_esiste]="Forum ID already exists";
$stringa[errore_id_forum_richiesto]="You must define a forum ID";
$stringa[errore_solo_lettere]="Only letters, number and _ can be used for an ID";
$stringa[errore_gruppo_corso_richiesto]="You have to select a course before creating a course forum";
$stringa[errore_lab_corso_richiesto]="You have to select a course before creating a lab forum";

$stringa[indirizzo_file_img]="Image file address";
$stringa[indirizzo_file_img_guida]="The address must start with <b>http://...</b> and point to a <b>.gif</b> or <b>.jpg</b> file.";
$stringa[elenco_img_alt]="Open the list of uploaded images to choose one or upload a new one.";
$stringa[elenco_img]="Uploaded images list";

$stringa[editor]="Editor";
$stringa[invia]="Send";
$stringa[lascia]="Drop";
$stringa[riprendi]="Take";
$stringa[nuovo_e]="New";
$stringa[salva]="Save";
$stringa[apri]="Open";

$stringa[errore_manca_id]="Missing ID";
$stringa[manca_id]="Missing ID";

$stringa[id_risorsa]="Resource ID";
$stringa[popup]="PopUp";
$stringa[larghezza_finestra]="Window width";
$stringa[altezza_finestra]="Window height";
$stringa[apro_link]="Link target";
$stringa[stessa_finestra]="in the same window";
$stringa[altra_finestra]="open another window";

$stringa[errore_id_esiste]="ID already exists";
$stringa[errore_manca_titolo]="Missing title";
$stringa[errore_manca_descrizione]="Missing description";
$stringa[errore_manca_file]="Missing file";

$stringa[errore_no_accesso_corso]="You're not authorized to access this course";
$stringa[errore_no_login]="You need to login to accessthis page.";
$stringa[errore_no_tutor]="You need to be tutor of at least one group to access this page";

$stringa[nuovo_messaggio]="New message";
$stringa[messaggio]="Message";

$stringa[errore_no_intervento_del]="Post not found";
$stringa[errore_no_intervento_del_altro]="You can delete your posts only";

$stringa[errore_file_rimosso]="File deleted or corrupted.";

$stringa[ricevuto_replica]="Your post got a reply in the following forum";
$stringa[leggi_replica]="You can read the post by clicking on the following link, written in a single line";

$stringa[messaggio_letto_da]="POST READ BY:";

$stringa[istruzioni_chat]="Chat Guide";
$stringa[faccine]="EmotIcons";
$stringa[non_verbali]="Non verbal expressions";
$stringa[non_verbali_guida]="By starting the line with a <b>+</b>, the rest of the phrase won't be viewed with the usual <b>user says</b> but just <i><b>user</b></i>. This way you can communicate something that you do (non verbal expressions, postures, emotions) and not that you say. 
For example the following line:<br> <b>+jumps happily up and down!</b>, will be shown as follows:<br><I><b>fleo</b> jumps happily up and down!</i>";
$stringa[immagini_chat]="Insert image";
$stringa[immagini_chat_guida]="You can insert in your line an uploaded image. All you have to do is writing the name of the image (without extensions) between asterisks. <br><br>For example by writing the following line:<br><br>Hi! Today i feel *baby3* ! <br><br>The image named <I>baby3.gif</i> or <i>baby3.jpg</i> (if exists) will be substituted and shown. By clicking on <b>Chat Images</b> you can get the list of uploaded images and upload new ones from your computer as well..";

$stringa[elenco_immagini_chat]="List of uploaded chat images";
$stringa[elenco_immagini_chat_guida]="To insert an image in your line simply put the name of the image in asterisks or click on <b>[Insert]</b> <br>
For example: <b>hi *baby3*</b>";
$stringa[carica_nuova_immagine]="Upload a new image";
$stringa[clicca_vederla]="click to enlarge...";

$stringa[errore_no_area]="Area doesn't exist";
$stringa[errore_no_parametri]="Invalid login";
$stringa[errore_no_pagina]="Sorry, page or resource non available";
$stringa[errore_solo_staff]="Staff only";
$stringa[errore_solo_admin]="Administrator only";
$stringa[errore_no_forum_disp]="Forum not available";
$stringa[errore_no_forum_accesso]="You can't access to this forum";
$stringa[errore_no_risorsa_accesso]="You can't access to this page or resource";

$stringa[scegli_colore]="Other colors...";

$stringa[esci]="Exit";
$stringa[entra_stanza]="enter this room";
$stringa[esce_stanza]="exit from this room";
$stringa[dice]="says";

$stringa[annulla]="Cancel";
$stringa[selezionato]="selected";
$stringa[colore_sfondo]="Background color";
$stringa[colore_sfondo_testata]="Header background color";
$stringa[bordo]="Border";
$stringa[altezza_cella]="Cell height";
$stringa[larghezza_cella]="Cell width";
$stringa[spazio_celle]="Cell spacing";
$stringa[margine_interno]="Cell padding";
$stringa[colonne]="Columns";
$stringa[righe]="Rows";

$stringa[utenti_attivi]="Active users in the last <b>10 minutes</b>";
$stringa[aggiorna]="Update";
$stringa[ultima_attivita]="Last activity";
$stringa[invita_chat]="Invite to chat";
$stringa[raggiungilo_chat]="join the user in the chat room";
$stringa[staff]="Staff";

$stringa[errore_no_dato]="Sorry, I can't find any user in Kairos using that data.";
$stringa[caro]="Dear";
$stringa[ecco_parametri]="here you have the login data for the Kairos of";
$stringa[scrivi_parametri]="Type the data exactly as they are, taking care of UPPERCASE and lowercase differences.\nThanks!";
$stringa[amministratore_area]="Area Administrator";
$stringa[pw_inviata]="OK, the password has just been sent to your email.";
$stringa[parametri_accesso]="Login data";

$stringa[utente_invitato]="User invited";
$stringa[utente_invitato_msg]="the user has been invited to join you.";
$stringa[chiude_da_sola]="This window will be closed within 5 seconds...";

$stringa[invito_chat]="Chat invitation";
$stringa[ricevuto_invito_chat]="You have been invited for a chat in the room";
$stringa[da_p]="from";
$stringa[declino]="Decline";

$stringa[editor_collaborativo]="Collaborative Editor";
$stringa[editor_finito]="You finished editing this page. Other users may now change it.";
$stringa[chiudi]="Close";
$stringa[replica]="Reply";

$stringa[messaggio_inviato]="Message sent.<br>Reload the private mail page to update it.";
$stringa[non_esiste]="doesn't exist";
$stringa[messaggio_inviato_fb]="Message sent";

$stringa[errore_manca_nome]="Missing name";
$stringa[errore_manca_cognome]="Missing surname";
$stringa[errore_manca_indirizzo]="Missing address";
$stringa[errore_manca_cap]="Missing ZIP";
$stringa[errore_manca_citta]="Missing City";
$stringa[errore_manca_prov]="Missing Prov.";
$stringa[errore_manca_scuola]="Missing School";
$stringa[errore_manca_telefono]="Missing telephone";
$stringa[errore_manca_email]="Missing E-Mail";
$stringa[errore_email_invalido]="Invalid E-Mail";
$stringa[errore_manca_eta]="Missing age";
$stringa[errore_manca_sesso]="Missing gender";
$stringa[errore_email_esiste]="E-Mail already in use";

$stringa[utente_si_e_registrato]="The following user has registered to your Kairos area";
$stringa[conferma_registrazione_guida]="To accept and confirm the registration you have to modify the corresponding record from the User Manager in the administrator area.";
$stringa[richiesta_registrazione]="registration required";
$stringa[grazie]="Thank you";
$stringa[richiesta_inoltrata]="You registration requiring has been forwarded to the area administrator.<br>The password will be sent to your email as soon as the registration will be confirmed.";
$stringa[benvenuto_demo]="Welcome to the demo area of Kairos:\n
http://www.garamond.it/kairos\nHere if follows your login data:";
$stringa[registrazione_demo]="Kairos demo registration";
$stringa[parametri_inviati]="The password has been sent to your email.";

$stringa[errore_manca_pw]="Missing Password";
$stringa[errore_solo_lettere_pw]="Only letters, number and _ can be used for the password";
$stringa[registrazione_man_fatta]="Registration done. Remember to inform the user of his/her login data.";

$stringa[errore_manca_testo]="Missing content";

$stringa[errore_manca_oggetto_newsl]="Missing the subject";
$stringa[errore_manca_testo_newsl]="Missing content of the message";

$stringa[anteprima_chat_collab]="Collaborative chat preview";
$stringa[errore_no_winie]="Sorry, Microsoft Internet Explorer 5.0 or later and Microsoft Windows 98 or later are required to use the collaborative editor.";
$stringa[edit_comunque]="Edit anyway";
$stringa[file_in_uso]="File in use by";
$stringa[anteprima_altra_finestra]="Preview in another window";

$stringa[indirizzo_file_suono]="URL of the audio file";
$stringa[indirizzo_file_suoni_guida]="The URL must start with <b>http://...</b> and point to a file of type: <b>.wav</b>, <b>.mid</b>, <b>.au</b>, <b>.asf</b>";
$stringa[elenco_suoni]="Uploaded audio files list";
$stringa[elenco_suoni_alt]="Open the list of uploaded audio files to choose one or upload a new one.";

$stringa[indirizzo_file_flash]="URL of the Flash file";
$stringa[indirizzo_file_flash_guida]="The URL must start with <b>http://...</b> and point to a file of type: <b>.swf</b>";
$stringa[elenco_flash]="Uploaded Flash files list";
$stringa[elenco_flash_alt]="Open the list of uploaded Flash files to choose one or upload a new one.";
$stringa[larghezza]="Width";
$stringa[altezza]="Height";

$stringa[indirizzo_file_video]="URL of the video file";
$stringa[indirizzo_file_video_guida]="The URL must start with <b>http://...</b> and point to a file of type: <b>.mpg</b>, <b>.avi</b>, <b>.mov</b>";
$stringa[elenco_video_alt]="Open the list of uploaded video files to choose one or upload a new one.";
$stringa[elenco_video]="Uploaded video files list(only 'wmv','mov','rpm', 'ogg', 'mp4' max 10 M)";

$stringa[utente_modificato]="User profile modified.";
$stringa[errore_esiste_domanda_allegato]="There's already a question of attach file type.";

$stringa[guarda_sito]="Look at your site";
$stringa[istruzioni]="Instructions";
$stringa[archivio_zip]="Upload .zip file";

$stringa[salva_file]="Save file";
$stringa[salva_file_in]="Save file in...";
$stringa[salva]="Save";
$stringa[pagina_salvata]="The file has been saved with the following URL";
$stringa[apri_file_selezionato]="Open selected file";
$stringa[apri_file]="Open file";

$stringa[file_gif_testata]="Header foreground image (.gif/.jpg):";
$stringa[file_gif_test_guida]="allowed size: exactly 78 pixels height - max 756 pixel width.";
$stringa[reimposta_default]="reset default";
$stringa[file_gif_sfondo]="Header background image (.gif/.jpg):";
$stringa[file_gif_sfondo_guida]="allowed size: 78 x 800 pixel";
$stringa[colore_testo]="Text:";
$stringa[colore_sfondo]="Background:";
$stringa[colore_bordi]="Border:";
$stringa[colore_testo_negativo]="Reversed text:";
$stringa[colore_link]="Link:";
$stringa[str1]="Text on white background";
$stringa[str2]="Reversed text";
$stringa[str3]="Small bold text";
$stringa[str4]="Plain text";

$stringa[errore_immagine_gif_testata]="The header foreground image must be .gif";
$stringa[errore_testata_max]="The header foreground image width must be max. 756 pixels";
$stringa[errore_testata_78]="The header foreground image height must be exactly 78 pixels";

$stringa[errore_immagine_gif_sfondo]="The header background image must be .gif";
$stringa[errore_sfondo_800]="he header background image width must be exactly 800 pixels";
$stringa[errore_sfondo_78]="The header background image height must be exactly 78 pixels";

$stringa[num_domande_random]="Number of random questions";
$stringa[punteggio_soglia]="Minimum score to consider the test achieved";
$stringa[test_superato]="Test achieved";
$stringa[test_non_superato]="Test not achieved";

$stringa[iscriviti_corsi]="Select the course you'd like to subcribe";

$stringa[utente_tutor]="User is tutor of the following groups";
$stringa[utente_corsi_attivi]="User subscribed to the following courses";

$stringa[contenuto_cartella]="Contents of folder";
$stringa[collega_pagine]="Insert into the folder links to the pages selected";
$stringa[repertorio_pagine]="Web pages repository linkable to the folder";

$stringa[download]="Download";

$stringa[database_lavori]="User Portfolio";
$stringa[principale]="root";
$stringa[nuovo_sito_web]="New web site";
$stringa[sito_web]="Web site";

$stringa[chi_scaricato]="Who have downloaded it?";
$stringa[chi_visto]="Who have seen it?";
$stringa[commenti]="Comments & Feedback";
$stringa[commenti_aggiungi]="Add a comment";
$stringa[scrivi_commento]="Type your comment or feedback";

$stringa[cerca_in]="Search in";
$stringa[tutti_corsi]="all courses";
$stringa[solo_corso]="selected course only";
$stringa[utenti]="Users";
$stringa[del_corso]="Course contents";
$stringa[degli_utenti]="User content";
$stringa[cerca_materiali]="Search contents";


$stringa[bacheca]="WebBoard";
$stringa[postit]="Post-it";
$stringa[mostra_nascondi]="Show/Hide";
$stringa[mostra]="Show";
$stringa[nascondi]="Hide";
$stringa[nuovo_p]="New";

$stringa[chiama_helpdesk]="For any help on the using of this site call <b>+39 064882110</b> or write to: <a href=mailto:supporto@garamond.it><b>supporto@garamond.it</b></a>";

$stringa[gestione_staff]="Staff Management";
$stringa[staff_direttore]="Staff Manager";
$stringa[staff_coordinatore]="Tutor responsabile ";
$stringa[staff_docente]="Teachers";
$stringa[staff_esperto]="Experts";
$stringa[staff_tutor]="Tutors";
$stringa[staff_autore]="Authors";
$stringa[aggiungi_staff]="Add usedr to staff";

$stringa[errore_no_utente]="User not found";

$stringa[invio_newsletter_globale]="Global newsletter";
$stringa[invio_newsletter_globale_label]="The message will be sent to all users in Kairos.";
$stringa[invio_newsletter_label]="The message will be sent to all users of the course.";

$stringa[appunti]="Notes";
$stringa[messaggio_inviato]="Message sent.";
$stringa[segna_come_letti]="Mark all as read";

$stringa[annulla_setcorso]="Unselect";
$stringa[annulla_setcorso_tip]="Unselect course context";

$stringa[esporta_iscritti]="Export list";
$stringa[project_work]="Web Portfolio";

$stringa[ruolo_scuola]="School Role";
$stringa[materia_insegnata]="Teaching Topic";
$stringa[guida_materia_insegnata]="required in the case you have selected role: \"Teacher\"";
$stringa[dirigente]="Headmaster";
$stringa[insegnante]="Teacher";
$stringa[studente]="Student";
$stringa[nessun_ruolo]="I don't work in school";

$stringa[errore_manca_materia]="Teaching Topic missed";

$stringa[autoiscrizione]="Self-subscription enabled";
$stringa[conf_canc]="Are you sure you want to delete it?";

$stringa[gestione_iscrizioni]="Course Subscriptions";
$stringa[cerca_registrati]="Search the users that you want to subscribe to the course";
$stringa[data_registrazione]="Registration date";
$stringa[cerca_iscritti]="Search the users subscribed to a course that you want to move or delete";
$stringa[data_iscrizione]="Subscription date";
$stringa[cancella_iscrizione]="Delete subscription";
$stringa[iscrizioni_trovate]="Subscriptions found";
$stringa[iscrivi_utenti_selezionati]="Subscribe selected users to the following course";
$stringa[sposta_iscrizioni_selezionate]="Move selected subscriptions to the following course";

$stringa[materiali_copia]="Copy resources from a course to another";
$stringa[corso_da_copiare]="Course origin";
$stringa[corso_su_copiare]="Course destination";

$stringa[report_corso]="Course - final report";
$stringa[livello_competenze]="Achieved level";
$stringa[superato_corso]="Completed flag";

$stringa[seleziona_edizione]="select edition";
$stringa[mia_cartella]="My Portfolio";
$stringa[cartella_utente]="Portfolio";

$stringa[stat_ok]="done";
$stringa[stat_processing]="processing";
$stringa[stat_wait]="waiting";

$stringa[stat_msg]="Your request will be processed as soon as possible (aprx. within 30-60 minutes). <br>
A message will be sent to your email when it will be done.<br>
Check the state of your request in the <b>Statistics</b> page.
<br>
Thank you.";

$stringa[max_7_giorni]="Date range must include max. <b>7 days</b>";
$stringa[max_30_giorni]="Date range must include max. <b>31 days</b>";

$stringa[tutti]="Show all";
$stringa[invia_staff]="Send a copy to the staff";

$stringa[editor_gruppi]="Editor groups";
$stringa[editor_attesa]="Staff users that you can add to the group";
$stringa[editor_iscritti]="Staff users added to the group";

$stringa[aggiungi_commento]="Add a comment to this page";
$stringa[btn_aggiungi_commento]="Add comment";
$stringa[lettore]="User";
$stringa[commenti_lettori]="Users' comments";

$stringa[gestione_contenuti]="Content Manager";
$stringa[utility]="Utility";
$stringa[gestione_edizioni]="Edition Manager";
$stringa[edizioni]="#Editions";
$stringa[iscrizione_utenti]="Course User subcriptions";
$stringa[gestione_gruppi]="Group manager";
$stringa[gestione_forum_comuni]="Common Forum Manager";
$stringa[iscrivi_utenti_selezionati]="Subscribe the selected users to the course";
$stringa[utenti_modifica]="Modify/Delete registered users";

$stringa[news_forum_comuni]="News from commom forums";
$stringa[news_forum_corso]="News from course forums";
$stringa[news_forum_gruppo]="News from group forums";
$stringa[news_forum_gruppo_pw]="News from project work forums";
$stringa[news_forum_gruppo_tutor]="News from the group forums you're tutoring";
$stringa[news_eventi]="Most recent and next events in calendar";
$stringa[news_portfolio]="Most recent contributions in user's portfolios";

$stringa[new_post]="new posts";
$stringa[utilities]="Utilities";
$stringa[visualizzazione]="View";
$stringa[struttura_intervento]="Thread";
$stringa[cartelle]="FOLDER";
$stringa[iscriviti]="Subscribe to this course";
$stringa[iscrizione_fatta]="l'iscrizione al corso e stata effettuata.";
$stringa[iscrizione_fatta_edizione_attiva]="Puoi gia frequentarne l'edizione attualmente attiva.";
$stringa[iscrizione_fatta_edizione_inattiva]="Dovrai attendere comunicazioni dal tutor per l'avvio dell'edizione del corso a cui sei stato iscritto.";

$stringa[url]="URL";
$stringa[posizione_news]="Posizione della notizia";
$stringa[errore_posizione_news]="Non hai indicato la posizione della notizia";

$stringa[gruppo_0]="Class";
$stringa[gruppo_1]="Project work";

$stringa[creato]="created";
$stringa[modificato]="modified";
$stringa[materiale_storia]="Object's operations history";
$stringa[lavori_gruppo]="Group works";
$stringa[componenti_gruppo]="Group members";

$stringa[forum_mail_on]="Notify to my email the new posts of this forum";
$stringa[forum_mail_off]="Stop notifying new posts of this forum to my email";

$stringa[forum_scritto_post]="A new post has been written on the forum";

$stringa["materiali_corso"]="Course Resources";
$stringa["materiali_comuni"]="Common Resources";
$stringa["materiali_gruppo"]="Group Resources";
$stringa[nome_organizzazione]="Organisation";

$stringa[seleziona_tutti]="Check all";
$stringa[deseleziona]="Uncheck";

$stringa[gestione_repository]="LO Repository";
$stringa[nuovo_lo]="New LO";
$stringa[lo]="LO";
$stringa[lo_tema_grafico]="Theme";
$stringa[lo_tipo]="LO type";
$stringa[cartella_sup]="In folder";
$stringa[nuovo_quiz]="New assessement";
$stringa[conf_cancella_verifica]="Are you sure that you want to delete this assessment?";
$stringa[importa_lo]="Import LO";

$stringa[materia]="Subject";
$stringa[argomenti]="Topics";
$stringa[obiettivi_didattici]="Learning Objectives";
$stringa[fruitore]="EndUser profile";
$stringa[competenze_ingresso]="Pre-requisites";

$stringa[titolo_lo_autore]="LO title and author";
$stringa[azioni]="Actions";
$stringa[lancia_lo]="LO Preview";
$stringa[traccia_lo]="LO Tracking";

$stringa[solo_testo]="Text only";
$stringa[testo_immagine]="Text and Image";
$stringa[testo_video]="Text and video";
$stringa[testo_flash]="Text and Flash animation";
$stringa[solo_immagine]="Image only";
$stringa[solo_video]="Video only";
$stringa[solo_flash]="Flash animation only";
$stringa[approfondimento]="pop-up page";
$stringa[template]="Template";

$stringa[audio_opzionale]="File audio opzionale";
$stringa[audio]="Audio File";
$stringa[img]="Image File";
$stringa[video]="Video File";
$stringa[flash]="Flash File";

$stringa[posizione_relativa]="Page Layout";
$stringa[colonna_destra_multiplo]="One or more objects in column on the right";
$stringa[colonna_sinistra_multiplo]="One or more objects in column on the left";
$stringa[testo_destra]="Object on the right";
$stringa[testo_sinistra]="Object on the left";
$stringa[colonna_destra]="Object in column on the right";
$stringa[colonna_sinistra]="Object in column on the left";
$stringa[colonna_grande_destra]="Big object in column on the right";
$stringa[colonna_grande_sinistra]="Big object in column on the left";
$stringa[sopra]="Object on the top";
$stringa[sotto]="Object on the bottom";
$stringa[alt_text]="Alternative text";

$stringa[alt_text]="Alternate Text";
$stringa[aggiungi_immagine]="Add image";
$stringa[elimina_immagine]="Delete";
$stringa[lo_tipo_lom]="LO type";
$stringa[esempio]="Examples";
$stringa[alt_img]="Alternate Image";

$stringa[questionari_corso]="Survey";
$stringa[riepilogo]="&egrave un riepilogo finale";
$stringa[lo_pubblicazione]="Course LO assignment";
$stringa[lo_non_pubblicati]="LO search (assignable)";
$stringa[lo_pubblicati]="LO assigned to the course";
$stringa[lo_corso]="Course LOs";
$stringa[lo_dafare]="TO DOs ";
$stringa[lo_fruizione]="LO - course stats";
$stringa[lo_f]="Status";

$stringa[link_tutoriale_alternativo]="Alternative page";
$stringa[link_tutoriale_ref]="Central Page";
$stringa[pag_glossario]="&egrave; Terms definitions";
$stringa[commento]="User comment";

$stringa[lo_modocontinua]="Allow bookmark and Lo continuation";
$stringa[lo_bloccoavanzamento]="Block forwarding during the test page";
$stringa[testo_geogebra]="Text and applet GeoGebra";
$stringa[elenco_geogebra]="Uploaded GeoGebra list/Upload new GeoGebra";
$stringa[ggb]="File ggb";


$stringa[it] = "Italiano";

$stringa[en] = "English";
$stringa[ro] = "Romana";
$stringa[us] = "English US";
$stringa[uk] = "English UK";

$stringa[registration_required0] = "For ID and PW e <br>you need to ";
$stringa[registration_required1] = "register";
$stringa[lo_viewer_Prerequisiti] = "Necessary knowledge";
$stringa[lo_viewer_Obbietivi] = "Objectives";
$stringa[lo_viewer_Argomenti] = "Subject";
$stringa[lo_viewer_Materia] = "Field";
$stringa[lo_viewer_lo_tipo] = "Lesson Type";
$stringa[aula_virtuale] = "Virtual Classroom";
$stringa[Repository] = "Repository";
$stringa[tools] = "Settings";
$stringa[consegna] = "Deadline";
$stringa[msg_ok_content] = "Correct! Proceed";
$stringa[msg_ko_content] = "Incorrect! Study!!";
$stringa[consegna] = "Deadline to ";
$stringa[msg_ok_content] = "Correct! Proceed";
$stringa[msg_ko_content] = "Incorrect! Study!!";
$stringa[sm_rs] ="SMRS";
$stringa[sm_rm] ="sm_rm";
$stringa[dragdrop] ="Drag Drop";
$stringa[cacciaerrore] = "Find the mistake";
$stringa[ascoltaescrivi] = "Listen and write";
$stringa[cruciverba] = "Complete this";
$stringa[guest_welcome] = "Hi, Guest!"
?>
