<?php
echo "
 <table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"1\" bgcolor=\"$colore_scuro\">
              <tr>
                <td width=\"10\" valign=\"top\" height=\"21\">&nbsp; </td>
                <td width=\"100%\" valign=\"middle\" class=\"testonegativo\" height=\"21\">
                  <div align=\"left\"><img src=\"img/ico_news.gif\" width=\"15\" height=\"15\" align=\"absmiddle\" hspace=\"5\">";


echo $stringa[news_iscritti];


echo "</div>
                </td>
                <td width=\"8\" valign=\"top\" height=\"21\">
                  <div align=\"right\"></div>
                </td>
              </tr>
";

?>
