<?php
echo "
<html>
<head>
<title>$titolo</title>
<meta name=\"keywords\" content=\"$parole_chiave\">
<meta name=\"description\" content=\"$descrizione\">
<script language=\"JavaScript\" src=\"script/funzioni.js\"></script>";

echo "
<link rel=\"stylesheet\" href=\"stili/$cod_area/stile_sito.css\">
</head>
";


echo "
<body topmargin=\"0\" leftmargin=\"15\" bgcolor=\"#FFFFFF\" link=\"#535190\">";

?>
