<p>

	<font face="verdana"><b>Cerca Riferimenti a Risorsa</b></font>

</p>

<p>

[<a href=index.php?risorsa=admin_index>Admin</a>]

</p>



<TABLE BORDER=0 ALIGN=left width=450>

<tr>

<td>

<form action="index.php" method="POST">

<input type=hidden name=risorsa value="lista_riferimenti_risorsa">

	<table border="0">		

    <tr>

            <td align="right"><font face="verdana" size="-1">Cerca riferimenti alla risorsa con identificativo:</font></td>

            <td><font face="verdana" size="-1"><input type="text"

            size="20" maxlength=100 name="id_risorsa_ref"></font></td>

     </tr>

    </table>

<br>

    <p align="center"><font face="verdana" size="-1"><input type="submit"

    value="CERCA">

    </font></p>

</form>

</td>

</tr>











</table>

<hr>
