<p>

<span class=titolopagina>Pagamento online</span><br>

</p>

<hr size=1>

<p>

<span class=testo>

Indica per favore l'importo che intendi pagare <br>e una descrizione della causale del pagamento. Ad esempio: "Saldo corso siti".

</span>

</p>

<form action=index.php method=post>

<input type=hidden name="risorsa" value="acquisto_online">

<input type=hidden name="cod_prodotto" value="saldo">

<span class=testo><b>Importo:</b></span> <input type=text name="prezzo" size=20>

<span class=testopiccoloblu>(la cifra espressa in Euro va indicata con un numero intero, senza centesimi)</span>

<br><br>

<span class=testo><b>Causale:</b></span><br>

<textarea name="causale" rows=5 cols=30></textarea>

<br><br>



<input type=submit value="Procedi">

</form>



<br>

<br>
