<table width="94%" align="center">

  <tr> 

    <td height="14" width="22%"> 

      <div align="center"></div>

    </td>

    <td height="14" width="78%"> 

      <span class="titolopagina">Segreteria</span>

	  <br><br>

	  <span class="sottotitolopagina">

	  Atlante Staff</span>

	  <br><br>



    </td>

  </tr>

  <tr> 

    <td width="22%"  valign="top"> 

      <ul>

        <li> 

          <span class="titololink"> 

		  <a href="index.php?risorsa=calendario">Calendario</a>

		  </span>

		  <br><br>

        </li>

	

		

      </ul>

    </td>

    <td width="78%" valign="top"> 

<p>

<span class=testo>

Dalla <b>Segreteria</b> puoi ottenere informazioni sul <a href="index.php?risorsa=calendario">Calendario</a> delle iniziative programmate.

</p>

<p>&nbsp;</p>

      </td>

  </tr>

</table>
