<?php

echo "

<html>

<head>

<title>$titolo</title>

<meta name=\"keywords\" content=\"$parole_chiave\">

<meta name=\"description\" content=\"$descrizione\">

<link rel=\"stylesheet\" href=\"stili/$cod_area/stile_sito.css\">

</head>

<body topmargin=\"0\" leftmargin=\"15\" bgcolor=\"#FFFFFF\" link=\"$colore_link\">";

echo "

<table width=\"100%\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" align=\"left\">

<tr><td>";

?>
